#!/usr/bin/env node
// generate-fluid.mjs — deterministic generator for every fluid-design style
// stack. Reads fluid.config.json (or the built-in defaults), and writes the
// stack files under assets/styles/. Re-running it with the same config
// produces byte-identical output: no timestamps, no non-deterministic
// ordering, no host-specific paths in the emitted text.
//
//   node generate-fluid.mjs [--config fluid.config.json] --stack tailwind-v4|css|scss|stylex|all [--out DIR] [--check]
//
// `--check` regenerates from the DEFAULT config (assets/fluid.config.json)
// and diffs the result against what's already on disk under assets/styles/,
// for every stack. It exits 1 and prints every differing/missing file if
// anything differs, 0 otherwise. It writes nothing.
//
// The committed assets/styles/* files are exactly this script's output for
// the default config — never hand-edit them; edit fluid.config.json (or this
// generator) and re-run.

import { mkdirSync, writeFileSync, readFileSync, readdirSync, existsSync } from 'node:fs'
import { dirname, join, resolve as resolvePath } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadConfig, mergeConfig, resolveFloors, cssUnits, num, DEFAULT_CONFIG_PATH, textZoomFactor, textZoomFactorExpr, textUnitExprRuntime } from './lib/fluid-math.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SKILL_ROOT = resolvePath(__dirname, '..')
const DEFAULT_OUT_DIR = join(SKILL_ROOT, 'assets/styles')
const FIXTURE_CONFIGS_DIR = join(__dirname, 'fixtures/configs')

const STACKS = ['tailwind-v4', 'css', 'scss', 'stylex', 'ts']

// ── shared text fragments ──────────────────────────────────────────────

function configSummary(cfg) {
  const floors = resolveFloors(cfg)
  const lines = [
    `reference ${num(cfg.reference.width)}x${num(cfg.reference.height)}, canvas ${num(cfg.canvas.width)}/${num(cfg.canvas.gutter)}, engageAt ${num(cfg.engageAt)}, heightAxis ${cfg.heightAxis}`,
    `fluid.floor ${num(floors.fluid)}`,
    `display.damping ${num(cfg.units.display.damping)} (floor ${cfg.units.display.floor === 'auto' ? `auto -> ${num(floors.display)}` : num(floors.display)})`,
    `copy.damping ${num(cfg.units.copy.damping)} (floor ${cfg.units.copy.floor === 'auto' ? `auto -> ${num(floors.copy)}` : num(floors.copy)})`,
    `chrome.enabled ${cfg.units.chrome.enabled}`,
    `ceiling ${cfg.ceiling === null ? 'none' : num(cfg.ceiling)}`,
    `zoomCompensation ${cfg.zoomCompensation}${cfg.zoomCompensation ? ` (fluid-text: full <= ${num(cfg.zoomTextRange[0])}, none >= ${num(cfg.zoomTextRange[1])})` : ''}`,
    `prefix "${cfg.prefix}"`
  ]
  return lines
}

function cssHeader(cfg, title) {
  const lines = [`GENERATED by fluid-design's generate-fluid.mjs — do not hand-edit.`, `Edit fluid.config.json and re-run:`, `  node scripts/generate-fluid.mjs --stack ${title}`, ``, `Config:`, ...configSummary(cfg).map((l) => `  ${l}`)]
  return `/**\n${lines.map((l) => ` * ${l}`).join('\n')}\n */\n\n`
}

function tsHeader(cfg, title) {
  const lines = [`GENERATED by fluid-design's generate-fluid.mjs — do not hand-edit.`, `Edit fluid.config.json and re-run:`, `  node scripts/generate-fluid.mjs --stack ${title}`, ``, `Config:`, ...configSummary(cfg).map((l) => `  ${l}`)]
  return `/**\n${lines.map((l) => ` * ${l}`).join('\n')}\n */\n\n`
}

function scssHeader(cfg, title) {
  const lines = [`GENERATED by fluid-design's generate-fluid.mjs — do not hand-edit.`, `Edit fluid.config.json and re-run:`, `  node scripts/generate-fluid.mjs --stack ${title}`, ``, `Config:`, ...configSummary(cfg).map((l) => `  ${l}`)]
  return `${lines.map((l) => (l === '' ? '//' : `// ${l}`)).join('\n')}\n\n`
}

function mdHeader(cfg, title) {
  const lines = configSummary(cfg)
  return `<!--\nGENERATED by fluid-design's generate-fluid.mjs — do not hand-edit.\nEdit fluid.config.json and re-run: node scripts/generate-fluid.mjs --stack ${title}\n\nConfig:\n${lines.map((l) => `  ${l}`).join('\n')}\n-->\n\n`
}

function rootBlock(units) {
  const lines = Object.entries(units.root).map(([k, v]) => `  ${k}: ${v};`)
  return `:root {\n${lines.join('\n')}\n}\n`
}

function engagedBlock(units, indent = '  ') {
  const lines = Object.entries(units.engaged).map(([k, v]) => `${indent}  ${k}: ${v};`)
  return `@media (width >= ${units.engageAt}px) {\n${indent}:root {\n${lines.join('\n')}\n${indent}}\n}\n`
}

const NOT_SCALED_NOTE = `NOT SCALED, deliberately:
  - border and stroke WIDTHS — a scaled 1px hairline is a blurry 1.5px one.
  - corner radii — there is nothing to scale on a square design.
  - tracking-*, letter-spacing — write it in \`em\`; that already follows
    font-size for free, so it never needs a fluid unit of its own.
  - standalone line-height outside the type utilities' own /lh modifier.
  - plain max-width TEXT MEASURES — those must stay fixed. A fixed measure
    is exactly why display type rides the gentler, damped curve instead of
    the base unit: a heading that shares a wrap-sensitive column with fixed
    body copy must not out-grow it.`

const UNITLESS_NOTE = `THE UNITLESS-NUMBER RULE: every value above is a bare number, never a
length. \`64px * var(--fluid)\` is invalid CSS — length multiplied by length
has no defined unit, so the browser drops the whole declaration, silently,
with no warning in the console. Always \`calc(64 * var(--fluid))\`: a
unitless number times a length (--fluid is 1px at the reference) resolves to
a length. This is the single most common way to lose one of these utilities
by hand-editing generated output — another reason not to.`

const NEGATIVES_NOTE = `NEGATIVES have no separate utility. Put the sign inside an arbitrary
value instead of doubling this file with a \`-<prefix>-top-*\` family that
only a handful of call sites would ever use:
  lg:top-[calc(-8*var(--fluid))]`

const ONE_SCALE_NOTE = `ONE SCALE, NO PER-SECTION RE-ANCHORING. A section drawn taller than the
reference cannot declare its own height as a local reference so that its
own \`N * var(--fluid)\` lands on 100svh again — that re-bases \`--fluid\`
without re-basing the type units with it (a rule that only sets --fluid
leaves --fluid-display on the ancestor's value; custom properties
substitute where they're DECLARED), so a display line's size would then
depend on how tall a NEIGHBOURING section happens to be drawn, not on the
viewport. A composition drawn taller than the reference is legitimately
more than one screen, at every viewport, by construction — making it fit is
a layout/content decision, not a units one.`

// Tailwind v4 has no tailwind.config to read a breakpoint LADDER from; it
// only has whatever `--breakpoint-*` tokens a project's own `@theme` block
// defines, and it falls back to its built-in defaults (in rem) for any name
// left undefined. It then orders every variant's generated CSS by comparing
// breakpoint LENGTHS. Two lengths in different units (a px override sitting
// next to Tailwind's rem defaults) cannot be compared, so Tailwind cannot
// place them in min-width order — measured: with only `--breakpoint-lg` set
// (in px), the entire `lg:` block was emitted BEFORE the `sm:` block, so
// `sm:text-[64px]` beat `lg:fluid-display-112` even though 1024px is wider
// than the 40rem `sm` breakpoint. The fix is not "use rem for lg too" (a
// media query in rem follows the visitor's browser font-size setting, while
// `fluid.css`'s own hand-written `(width >= engageAt px)` query does not, so
// the two would silently disagree at any zoom level other than 100%) — it
// is to define the WHOLE ladder in one unit, px, so every value is
// comparable and sorts correctly regardless of which one a project happens
// to override.
//
// `lg` is pinned to `engageAt` (see the invariant elsewhere in this file:
// the Tailwind breakpoint and the scale's own engage point must be one
// number, not three copies that can drift). The other four rungs keep
// Tailwind's own px-equivalents of its defaults (sm 640, md 768, xl 1280,
// 2xl 1536) UNLESS `engageAt` collides with or crosses one of them, in which
// case that rung (and any rung past it, cascading) is nudged just past its
// neighbour so the ladder stays strictly increasing. `lg` itself never
// moves — only the stock rungs around it do.
function buildBreakpointLadder(engageAt) {
  const lg = engageAt
  let sm = 640
  let md = 768
  let xl = 1280
  let xxl = 1536
  const notes = []

  if (md >= lg) {
    const adjusted = Math.max(1, lg - 1)
    notes.push(`md (default 768px) would land at or past lg/engageAt (${lg}px); narrowed to ${adjusted}px to keep sm < md < lg.`)
    md = adjusted
  }
  if (sm >= md) {
    const adjusted = Math.max(1, md - 1)
    notes.push(`sm (default 640px) would land at or past md (${md}px); narrowed to ${adjusted}px to keep sm < md.`)
    sm = adjusted
  }
  if (xl <= lg) {
    const adjusted = lg + 1
    notes.push(`xl (default 1280px) would land at or before lg/engageAt (${lg}px); widened to ${adjusted}px to keep lg < xl < 2xl.`)
    xl = adjusted
  }
  if (xxl <= xl) {
    const adjusted = xl + 1
    notes.push(`2xl (default 1536px) would land at or before xl (${xl}px); widened to ${adjusted}px to keep xl < 2xl.`)
    xxl = adjusted
  }

  return { sm, md, lg, xl, xxl, notes }
}

function breakpointThemeBlock(cfg) {
  const ladder = buildBreakpointLadder(cfg.engageAt)
  const lines = [
    `--breakpoint-sm: ${num(ladder.sm)}px;`,
    `--breakpoint-md: ${num(ladder.md)}px;`,
    `--breakpoint-lg: ${num(ladder.lg)}px; /* == engageAt. fluid.css's own media query is hand-written as`,
    `     \`@media (width >= ${num(cfg.engageAt)}px)\` -- it has no Tailwind config to read a`,
    `     breakpoint from -- so if you move \`engageAt\` you must move this token by`,
    `     hand too, or the two silently disagree about where the site turns into a`,
    `     fixed 1px scale. */`,
    `--breakpoint-xl: ${num(ladder.xl)}px;`,
    `--breakpoint-2xl: ${num(ladder.xxl)}px;`
  ]
  const noteBlock =
    ladder.notes.length > 0
      ? `\n  /* Ladder adjusted to stay monotonic for this engageAt:\n${ladder.notes.map((n) => `     - ${n}`).join('\n')}\n  */`
      : ''
  return { lines, noteBlock, ladder }
}

function floorAndArmNote(cfg) {
  const floors = resolveFloors(cfg)
  const ratio = num(cfg.engageAt / cfg.reference.width)
  return `WHY min(), NOT max(): the two axes must COMBINE as a "contain" fit — the
tighter axis wins — which is what makes "never taller than the viewport"
unconditional. max() would be "cover", letting a section outgrow the window
on whichever axis lost.

WHY svh, NOT dvh: dvh resizes as a mobile browser's chrome collapses
mid-scroll, which would resize type mid-gesture — over anything
scroll-driven, the worst possible surface for a layout thrash. svh is the
SMALLEST viewport height and does not move once the page has loaded.

FLOOR DERIVATION (the "auto" floors in fluid.config.json): a damped type
unit's floor is not picked, it is READ OFF the damped curve at \`engageAt\`
— the value the role hands over at the exact breakpoint where the whole
scale flattens to 1px and a fixed mobile layout takes over:
  engageAt / reference.width = ${ratio}
  display: ${num(cfg.units.display.damping)} * ${ratio} + ${num(1 - cfg.units.display.damping)} -> floor ${num(floors.display)}
  copy:    ${num(cfg.units.copy.damping)} * ${ratio} + ${num(1 - cfg.units.copy.damping)} -> floor ${num(floors.copy)}
The base --fluid floor (${num(floors.fluid)}) is different in kind: it is
CHOSEN, not derived — the layout height at which the composition itself
should stop compressing further — because the base unit has no upstream
curve to read a handover value from.

THE CHROME UNIT (--fluid-chrome): site chrome (header, footer, dropdowns)
must never shrink on a short-but-wide window, where height would otherwise
bind and shrink the whole layout unit — but it still has to shrink when
WIDTH binds, or it stops fitting at engageAt. That is width-always,
height-never-below-1: \`min(widthArm, max(1px, heightArm))\`. It is spent
explicitly at call sites (\`calc(N * var(--fluid-chrome))\`) — there is no
parallel \`${cfg.prefix}-chrome-*\` utility family, on purpose: chrome is a
small, fixed set of call sites, not a general layout concern.`
}

const FOUR_INVARIANTS_NOTE = `FOUR INVARIANTS. Breaking any one stops this being a scale:
  1. --fluid stays purely proportional on both arms, no intercept — that is
     what makes \`900 * var(--fluid)\` resolve to exactly \`100svh\` while
     height binds, landing a section on exactly one screen.
  2. \`reference\` is a CONTENT budget, not the drawn canvas — it is
     deliberately narrower than \`canvas.width\` so desktop content fits a
     typical window; between the two the composition does not scale at all
     (the height arm pins the factor at 1.0), it just gets more room.
  3. The two axes combine with min(), never max() — see below.
  4. svh, never dvh — see below.
Below \`engageAt\` every one of these is a flat 1px, so every value under
that breakpoint is completely untouched — the system is desktop-only by
design.`

// ── tailwind-v4 ─────────────────────────────────────────────────────────

function buildUtilityBlock(prefix, cfg) {
  const p = prefix
  return `/* ── Utilities that spend the fluid units ───────────────────────────────
   One @utility per property. The VALUE is always the drawn number, inline
   at the call site — nothing is pre-registered, any number (including
   decimals) works. \`lg:${p}-py-120\` is 120 design px of block padding,
   scaled by --fluid.

   NAMING: every utility is \`${p}-\` plus the name Tailwind already uses for
   that property (\`${p}-p-*\` is \`p-*\`, \`${p}-size-*\` is \`size-*\` — width
   AND height, exactly as Tailwind's own \`size-*\` — \`${p}-text-*\` is
   \`text-*\`, font-size). Nothing here invents a word where Tailwind has
   one, so the only thing left to know is WHICH UNIT a class spends.

   \`${p}-cap-*\` is the one exception, and earns it by behaving differently:
   it is a max-width that only ever GROWS, never an ordinary max-width.

${NEGATIVES_NOTE.split('\n').map((l) => '   ' + l).join('\n')}

${NOT_SCALED_NOTE.split('\n').map((l) => '   ' + l).join('\n')}
*/

/* Padding — full set, every axis and side. A half-set (say, missing pl/pr)
   is an oversight waiting to be found by whoever needs the missing side. */
@utility ${p}-p-* {
  padding: calc(--value(number) * var(--fluid));
}
@utility ${p}-px-* {
  padding-inline: calc(--value(number) * var(--fluid));
}
@utility ${p}-py-* {
  padding-block: calc(--value(number) * var(--fluid));
}
@utility ${p}-pt-* {
  padding-top: calc(--value(number) * var(--fluid));
}
@utility ${p}-pb-* {
  padding-bottom: calc(--value(number) * var(--fluid));
}
@utility ${p}-pl-* {
  padding-left: calc(--value(number) * var(--fluid));
}
@utility ${p}-pr-* {
  padding-right: calc(--value(number) * var(--fluid));
}

/* Margin — same full-set reasoning as padding. */
@utility ${p}-m-* {
  margin: calc(--value(number) * var(--fluid));
}
@utility ${p}-mx-* {
  margin-inline: calc(--value(number) * var(--fluid));
}
@utility ${p}-my-* {
  margin-block: calc(--value(number) * var(--fluid));
}
@utility ${p}-mt-* {
  margin-top: calc(--value(number) * var(--fluid));
}
@utility ${p}-mb-* {
  margin-bottom: calc(--value(number) * var(--fluid));
}
@utility ${p}-ml-* {
  margin-left: calc(--value(number) * var(--fluid));
}
@utility ${p}-mr-* {
  margin-right: calc(--value(number) * var(--fluid));
}

@utility ${p}-gap-* {
  gap: calc(--value(number) * var(--fluid));
}
@utility ${p}-gap-y-* {
  row-gap: calc(--value(number) * var(--fluid));
}
/* gap-x scales too — horizontal space INSIDE a box that itself scales is
   part of the drawing, same as vertical space. (Space between page-level
   COLUMNS is a different call: that's a page-gutter concern and should
   follow the breakpoint, not this scale — leave that plain \`gap-x-*\`.) */
@utility ${p}-gap-x-* {
  column-gap: calc(--value(number) * var(--fluid));
}

@utility ${p}-w-* {
  width: calc(--value(number) * var(--fluid));
}
@utility ${p}-h-* {
  height: calc(--value(number) * var(--fluid));
}
/* Square: width AND height in one utility, for icons and marks — a fixed
   16px icon beside type that scales reads 30% small on a large display. */
@utility ${p}-size-* {
  width: calc(--value(number) * var(--fluid));
  height: calc(--value(number) * var(--fluid));
}
/* A floor that scales. \`${p}-min-w-166\` on a button primitive is that
   component's frame width — left fixed it would stop being a floor once
   the rest of the composition has outgrown it. */
@utility ${p}-min-w-* {
  min-width: calc(--value(number) * var(--fluid));
}
@utility ${p}-min-h-* {
  min-height: calc(--value(number) * var(--fluid));
}
@utility ${p}-max-h-* {
  max-height: calc(--value(number) * var(--fluid));
}

/* A width CAP that only ever grows. Below the reference the drawn number
   already fits the viewport and shrinking it would narrow the composition
   on exactly the screens that need the room; above it the cap has to scale
   or the frame gets taller without getting wider. */
@utility ${p}-cap-* {
  max-width: max(calc(--value(number) * 1px), calc(--value(number) * var(--fluid)));
}

/* Offsets for absolutely-positioned parts drawn at fixed coordinates inside
   a composition that scales — \`inset-0\` and percentage offsets need none
   of this; zero and 50% are already relative. */
@utility ${p}-inset-* {
  inset: calc(--value(number) * var(--fluid));
}
@utility ${p}-top-* {
  top: calc(--value(number) * var(--fluid));
}
@utility ${p}-right-* {
  right: calc(--value(number) * var(--fluid));
}
@utility ${p}-bottom-* {
  bottom: calc(--value(number) * var(--fluid));
}
@utility ${p}-left-* {
  left: calc(--value(number) * var(--fluid));
}

/* Writes the independent \`translate\` property, not \`transform\`, so it
   composes with a transform a motion library writes per frame instead of
   fighting it for the same property. */
@utility ${p}-translate-x-* {
  --tw-translate-x: calc(--value(number) * var(--fluid));
  translate: var(--tw-translate-x) var(--tw-translate-y);
}
@utility ${p}-translate-y-* {
  --tw-translate-y: calc(--value(number) * var(--fluid));
  translate: var(--tw-translate-x) var(--tw-translate-y);
}

/* Type. The \`/\` modifier is Tailwind's own \`text-lg/7\` idiom:
   \`${p}-display-64/72\` is 64px type on a 72px line box, BOTH scaled
   together. Omit it and only font-size is emitted.
   \`${p}-display-*\` and \`${p}-copy-*\` spend the damped type units;
   \`${p}-text-*\` spends the BASE unit, for type whose container scales on
   it too — type on the gentler curve inside a box on the steeper one
   outgrows its box and re-wraps.${cfg.zoomCompensation ? `
   Browser zoom: display and copy zoom 1:1 through their units. \`${p}-text-*\`
   takes a share of the zoom by size — all of it up to ${num(cfg.zoomTextRange[0])}px drawn,
   none from ${num(cfg.zoomTextRange[1])}px — because its box does not zoom, and big type
   zoomed inside it runs over its neighbours (zoomTextRange, fluid-scale.md §12).` : ''} */
@utility ${p}-display-* {
  font-size: calc(--value(number) * var(--fluid-display));
  line-height: calc(--modifier(number) * var(--fluid-display));
}
@utility ${p}-copy-* {
  font-size: calc(--value(number) * var(--fluid-copy));
  line-height: calc(--modifier(number) * var(--fluid-copy));
}
@utility ${p}-text-* {
  font-size: calc(--value(number) * ${textUnitExprRuntime(cfg, '--value(number)')});
  line-height: calc(--modifier(number) * ${textUnitExprRuntime(cfg, '--value(number)')});
}
`
}

const BREAKPOINT_TRAP_NOTE = `TAILWIND v4's BREAKPOINT-ORDERING TRAP: there is no tailwind.config to read a
breakpoint LADDER from -- only whatever @theme tokens a project defines, with
Tailwind's own rem defaults filling in anything left undefined. Utilities are
then emitted in min-width order by comparing breakpoint LENGTHS, and a px
value cannot be compared against a rem one. Defining ONLY --breakpoint-lg (in
px) while sm/md/xl/2xl stay on Tailwind's rem defaults means the whole lg:
block sorts before the sm: block regardless of which is visually wider --
measured: sm:text-[64px] beat lg:fluid-display-112 even though 1024px > the
40rem sm breakpoint. The @theme block below defines the FULL ladder in one
unit (px) for exactly this reason -- not just the one rung this project
cares about.`

function buildTailwindFluidCss(cfg) {
  const units = cssUnits(cfg)
  const bp = breakpointThemeBlock(cfg)
  return (
    cssHeader(cfg, 'tailwind-v4') +
    `/* Import this AFTER "tailwindcss": @import 'tailwindcss'; @import './fluid.css';
   The @utility rules below need Tailwind's utility layer already registered.

${FOUR_INVARIANTS_NOTE.split('\n').map((l) => '   ' + l).join('\n')}

   Scope is the whole site from \`${cfg.prefix === 'fluid' ? 'lg' : cfg.prefix}\`-breakpoint up — every route, every
   shared element, prose, forms, chrome. What stays off the scale is a list
   of PROPERTIES, not pages (see the utility block below).

${floorAndArmNote(cfg).split('\n').map((l) => '   ' + l).join('\n')}

${UNITLESS_NOTE.split('\n').map((l) => '   ' + l).join('\n')}

${BREAKPOINT_TRAP_NOTE.split('\n').map((l) => '   ' + l).join('\n')}
*/

@theme {
  ${bp.lines.join('\n  ')}${bp.noteBlock}
}

${rootBlock(units)}
${engagedBlock(units)}
${ONE_SCALE_NOTE.split('\n').map((l) => '/* ' + l).join('\n') + ' */\n'}
${buildUtilityBlock(cfg.prefix, cfg)}`
  )
}

function buildTokensExampleCss(cfg) {
  return (
    cssHeader(cfg, 'tailwind-v4') +
    `/* tokens.example.css — an EXAMPLE, not your brand. Copy the shape, replace
   the ramp and the role aliases with your own palette. This is what "reach
   for the semantic name, not the brand ramp" (surface/text/border/icon
   roles aliasing a brand ramp) looks like wired up.

   The --breakpoint-* ladder does NOT live here. It is infrastructure, not
   brand, so it ships in fluid.css's own @theme block (the full sm/md/lg/xl/
   2xl ladder, all in px — see the trap note there). Defining a lone
   --breakpoint-lg in a second @theme block is exactly the bug that trap
   note describes: it would leave sm/md/xl/2xl on Tailwind's rem defaults,
   mixing units and breaking Tailwind's variant ordering. Never redeclare
   --breakpoint-* here.
*/
@theme {
  /* ── Brand ramp — replace ──────────────────────────────────────────── */
  --color-brand-navy-900: #0b1220;
  --color-brand-navy-700: #1c2b45;
  --color-brand-gold-500: #fccc36;
  --color-brand-neutral-white: #ffffff;
  --color-brand-neutral-black: #000000;

  /* ── Semantic roles — components use THESE, never the ramp above ─────
     Four traps below, all of which compile and render as plausible design
     decisions. None of them error — \`pnpm kit:lint\`-equivalent tooling (a
     lint rule banning raw brand-ramp classes outside this file) is what
     catches them, not the compiler. */
  --color-surface-dark: var(--color-brand-navy-900);
  --color-surface-light: var(--color-brand-neutral-white);
  --color-text-heading: var(--color-brand-neutral-white);
  --color-text-body: var(--color-brand-navy-700);
  --color-border-primary: var(--color-brand-navy-700);
  --color-icon-default: var(--color-brand-navy-700);
  --focus-ring: var(--color-brand-gold-500);

  /* Trap 1: \`rounded-*\` still rounds. Defining a token at 0 ADDS a utility
     (\`rounded-custom\`) — it does not reset Tailwind's existing radius
     scale, so \`rounded-lg\` etc. keep rounding right next to it. */
  --radius-custom: 0px;

  /* Trap 2: there is no \`dark:\` mode here (no \`@custom-variant dark\`
     declared), so if a component reaches for \`dark:bg-surface-dark\`
     anyway, Tailwind compiles it to a bare
     \`@media (prefers-color-scheme: dark)\` query that fires for every
     visitor whose OS theme is dark — not a manual toggle. Either declare
     \`@custom-variant dark\` for real, or never write \`dark:\` at all. */

  /* Trap 3: a utility whose token does not exist emits NOTHING and Tailwind
     never warns. \`bg-brand-teal-500\` with no \`--color-brand-teal-500\`
     above silently produces an empty rule — it looks wired up in the
     markup and does nothing in the browser. */

  /* Trap 4: a name shared with another codebase can mean something else
     there. \`--color-app-*\` in a sibling design-system package, or
     \`border-border-secondary\` in a different app, is not guaranteed to be
     this ramp — check before reusing a token NAME across projects. */
}
`
  )
}

function buildCnTs(cfg) {
  const p = cfg.prefix
  const groupsSpacing = [
    ['p', 'p'], ['px', 'px'], ['py', 'py'], ['pt', 'pt'], ['pb', 'pb'], ['pl', 'pl'], ['pr', 'pr'],
    ['m', 'm'], ['mx', 'mx'], ['my', 'my'], ['mt', 'mt'], ['mb', 'mb'], ['ml', 'ml'], ['mr', 'mr'],
    ['gap', 'gap'], ["'gap-x'", 'gap-x'], ["'gap-y'", 'gap-y']
  ]
  const spacingLines = groupsSpacing.map(([group, suffix]) => `      ${group}: [fluid('${p}-${suffix}')],`).join('\n')
  return (
    tsHeader(cfg, 'tailwind-v4') +
    `import { type ClassValue, clsx } from 'clsx'
import { extendTailwindMerge } from 'tailwind-merge'

/**
 * \`tailwind-merge\` resolves conflicts from a table of class groups it ships
 * with. \`${p}-*\` utilities are not in that table, so out of the box it
 * treats every one of them as an unknown class and keeps ALL of them:
 *
 *   twMerge('lg:${p}-p-40 lg:${p}-p-24')  ->  BOTH survive
 *   twMerge('lg:w-[380px] lg:${p}-w-560') ->  BOTH survive
 *
 * Two declarations of the same property then both reach the browser, and
 * CSS SOURCE ORDER decides which wins — not the order they were written in
 * the class string. That is the opposite of what every caller assumes when
 * they pass \`className\` to override a component's default, and it stays
 * invisible right up until a shared component starts accepting
 * \`className\` on top of its own fluid classes.
 *
 * So each family is registered into the Tailwind class group its property
 * already belongs to: \`${p}-p-*\` joins \`p\`, \`${p}-w-*\` joins \`w\`, and all
 * three font-size families join \`font-size\`, which additionally makes
 * them conflict with EACH OTHER — \`${p}-text-14 ${p}-copy-14\` then
 * resolves to the last one instead of shipping two font sizes.
 */

// Every fluid utility takes a bare number, optionally with Tailwind's \`/\`
// line-height modifier: \`${p}-p-40\`, \`${p}-text-14\`, \`${p}-text-14/18\`.
// Decimals are allowed — the scale accepts any drawn number.
const isFluidValue = (value: string) => /^\\d+(\\.\\d+)?(\\/\\d+(\\.\\d+)?)?$/.test(value)

const fluid = (name: string) => ({ [name]: [isFluidValue] })

export const twMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      // Spacing
${spacingLines}

      // Box
      w: [fluid('${p}-w')],
      h: [fluid('${p}-h')],
      size: [fluid('${p}-size')],
      'min-w': [fluid('${p}-min-w')],
      'min-h': [fluid('${p}-min-h')],
      'max-h': [fluid('${p}-max-h')],
      // \`${p}-cap-*\` IS a max-width, however differently it behaves (it
      // only ever grows). A plain \`max-w-*\` next to it is still a conflict.
      'max-w': [fluid('${p}-cap')],

      // Type — all three land in ONE group on purpose: they are three
      // units for one property, so two of them on one element is always a
      // mistake, never an intentional pair.
      'font-size': [fluid('${p}-text'), fluid('${p}-copy'), fluid('${p}-display')],

      // Position
      inset: [fluid('${p}-inset')],
      top: [fluid('${p}-top')],
      right: [fluid('${p}-right')],
      bottom: [fluid('${p}-bottom')],
      left: [fluid('${p}-left')],

      'translate-x': [fluid('${p}-translate-x')],
      'translate-y': [fluid('${p}-translate-y')]
    }
  }
})

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
`
  )
}

function buildTailwindReadme(cfg) {
  return (
    mdHeader(cfg, 'tailwind-v4') +
    `# fluid-design — Tailwind v4 stack

\`fluid.css\` is a Tailwind v4 stylesheet: \`:root\` units, the engage media
query, and the full \`@utility\` vocabulary (\`${cfg.prefix}-p-*\`,
\`${cfg.prefix}-display-*\`, \`${cfg.prefix}-cap-*\`, …). Import it **after**
Tailwind itself, since \`@utility\` needs Tailwind's utility layer already
registered:

\`\`\`css
@import 'tailwindcss';
@import './fluid.css';
@import './tokens.example.css'; /* optional — replace with your own tokens */
@import '../shared/base.css' layer(base);
\`\`\`

**\`shared/base.css\` needs \`layer(base)\`, or it beats every Tailwind utility.**
An import with no \`layer(...)\` is unlayered CSS, and unlayered CSS wins
against every declaration inside Tailwind's own \`@layer\` blocks regardless
of selector specificity or source order — so \`base.css\`'s \`:focus-visible\`
outline, its \`button { cursor: pointer }\`, etc. would silently override
component-level utilities meant to win. Assigning it to the \`base\` layer
puts it exactly where Tailwind's own Preflight resets live, so ordinary
utility-beats-base cascade rules apply instead.

There is no \`tailwind.config\`; everything is \`@theme\`/\`@utility\` in CSS
(v4's model). \`tokens.example.css\` shows the semantic-token convention this
skill assumes elsewhere (references/tokens-and-theming.md) and calls out the four traps
that compile silently wrong: \`rounded-*\` still rounding past a 0 radius
token, an unguarded \`dark:\`, a utility whose token doesn't exist, and a
name that means something else in another codebase.

\`cn.ts\` registers every \`${cfg.prefix}-*\` family into \`tailwind-merge\`'s
class groups. Without it, \`cn('lg:${cfg.prefix}-p-40', className)\` lets
BOTH declarations reach the browser when \`className\` also sets padding —
CSS source order decides the winner instead of the override the caller
clearly intended. Use \`cn\` (or fold this registration into your own) on
every component that accepts \`className\` alongside a fluid utility.

## Values are the drawn number

\`lg:${cfg.prefix}-py-120\` is 120 design px of block padding, scaled — write
the number straight from your design file, decimals included. Negatives have
no separate utility; put the sign inside an arbitrary value:
\`lg:top-[calc(-8*var(--fluid))]\`.

## Regenerating

Both files are generated from \`assets/fluid.config.json\` — edit the config,
not these files, and re-run:

\`\`\`
node scripts/generate-fluid.mjs --stack tailwind-v4
\`\`\`
`
  )
}

// ── css (vanilla) ───────────────────────────────────────────────────────

function buildUnitsOnlyCss(cfg, headerComment) {
  const units = cssUnits(cfg)
  return (
    headerComment +
    `${FOUR_INVARIANTS_NOTE.split('\n').map((l) => '/* ' + l).join('\n') + ' */\n\n'}` +
    `${rootBlock(units)}\n${engagedBlock(units)}\n` +
    `${floorAndArmNote(cfg).split('\n').map((l) => '/* ' + l).join('\n') + ' */\n\n'}` +
    `${UNITLESS_NOTE.split('\n').map((l) => '/* ' + l).join('\n') + ' */\n'}`
  )
}

function buildVanillaCss(cfg) {
  const p = cfg.prefix
  return (
    buildUnitsOnlyCss(cfg, cssHeader(cfg, 'css')) +
    `\n/* .${p}-frame — the drawn frame, cap + scaled gutter on ONE box. Apply it
   ONCE PER SECTION, to that section's own single inner wrapper — never to
   the page as a whole, and never stacked on a second box nested inside the
   same section: the section itself carries full-bleed colour, and this box
   carries the frame (references/section-recipe.md). Below engageAt it is a
   plain full-width box with a fixed measure and a fixed gutter (32px from
   640px up); the cap and the scaled gutter both engage together above it. */
.${p}-frame {
  width: 100%;
  margin-inline: auto;
  max-width: ${num(cfg.canvas.width)}px;
  padding-inline: 24px;
}
@media (width >= 640px) {
  .${p}-frame {
    padding-inline: 32px;
  }
}
@media (width >= ${cfg.engageAt}px) {
  .${p}-frame {
    margin-inline: auto;
    max-width: max(${num(cfg.canvas.width)}px, calc(${num(cfg.canvas.width)} * var(--fluid)));
    padding-inline: calc(${num(cfg.canvas.gutter)} * var(--fluid));
  }
}
`
  )
}

function buildVanillaReadme(cfg) {
  return (
    mdHeader(cfg, 'css') +
    `# fluid-design — vanilla CSS stack

\`fluid.css\` is framework-free: the \`:root\` units, the engage media query,
\`--header-h\`, and \`.${cfg.prefix}-frame\` (the drawn frame as a cap + a
scaled gutter, on one box).

## Include \`shared/base.css\` too — box-sizing

This stack ships no reset of its own, so \`shared/base.css\`'s \`*, *::before,
*::after { box-sizing: border-box }\` rule is not optional here the way it
is under Tailwind (whose own Preflight already sets it). Without it,
\`.${cfg.prefix}-frame\`'s \`max-width\` caps the CONTENT box instead of the
border box, and the frame renders at canvas + 2×gutter — wider than drawn,
with its contents overflowing the intended edge. Include \`shared/base.css\`
before this file, or add the box-sizing rule yourself if you already reset
some other way.

## The authoring convention

There is no Tailwind here to hand you \`lg:\` variants or arbitrary-value
classes, so a component's fluid rules live inside the SAME media query the
units engage in, spending \`calc(N * var(--fluid...))\` with the drawn number
inline:

\`\`\`css
.card {
  /* mobile: your own fixed values */
  padding: 16px;
  font-size: 16px;
}

@media (width >= ${cfg.engageAt}px) {
  .card {
    padding: calc(40 * var(--fluid));
    font-size: calc(18 * var(--fluid-copy));
  }
}
\`\`\`

## Why there are no arbitrary-value classes here

The Tailwind stack's \`${cfg.prefix}-p-40\` is sugar over exactly this
\`calc()\` — a class per utility, generated once, applied everywhere. Vanilla
CSS has no utility-class layer to generate into, and inventing one (a
build step emitting thousands of single-property classes) would just be a
worse, unmaintained copy of Tailwind's own \`@utility\` engine. Write the
\`calc()\` at the one component rule that needs it; there is no second
occurrence to justify a class for it (the second-consumer rule, stated in the scroll-animation skill's references/motion-architecture.md §2 — "a
pattern becomes reusable at its SECOND consumer, never its first").

## Why mobile values stay separate, not derived

Below \`${cfg.engageAt}px\` every fluid unit is a flat \`1px\`, so
\`calc(16 * var(--fluid))\` BELOW the breakpoint is just \`16px\` — you could
technically write the mobile rule with the same \`calc()\` and rely on the
flat unit. Don't: mobile layout is usually a genuinely different
composition (stacked, not scaled — fewer columns, different spacing
rhythm), not a smaller version of the desktop one, so its numbers are
independent values that happen to also be static, not the same drawing
shrunk down. Writing them as plain px says that plainly; writing them as
\`calc(N * var(--fluid))\` implies a relationship to the desktop numbers
that does not exist.

## Regenerating

Generated from \`assets/fluid.config.json\`:

\`\`\`
node scripts/generate-fluid.mjs --stack css
\`\`\`
`
  )
}

// ── scss ────────────────────────────────────────────────────────────────

function buildScss(cfg) {
  const floors = resolveFloors(cfg)
  const p = cfg.prefix
  const units = cssUnits(cfg)
  // Every property in `units.root`/`units.engaged` is emitted verbatim below
  // — no hand-written expression duplicates cssUnits(cfg)'s formulas, so a
  // ceiling, a disabled chrome unit, or any other config knob can never
  // diverge between this stack and the others (the SCSS emitter's previous
  // hand-rolled block silently ignored `ceiling` and built the literal
  // string `--fluid-fluid` when chrome was disabled).
  const rootLines = Object.entries(units.root)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n')
  const engagedLines = Object.entries(units.engaged).map(([k, v]) => `    ${k}: ${v};`).join('\n')
  return (
    scssHeader(cfg, 'scss') +
    `@use 'sass:math';

// ── Config variables — mirror fluid.config.json; regenerate, don't edit ──
$fluid-prefix: '${p}';
$fluid-reference-width: ${num(cfg.reference.width)};
$fluid-reference-height: ${num(cfg.reference.height)};
$fluid-canvas-width: ${num(cfg.canvas.width)};
$fluid-canvas-gutter: ${num(cfg.canvas.gutter)};
$fluid-engage-at: ${num(cfg.engageAt)}px;
$fluid-height-axis: ${cfg.heightAxis};
$fluid-floor: ${num(floors.fluid)};
$fluid-display-damping: ${num(cfg.units.display.damping)};
$fluid-display-floor: ${num(floors.display)};
$fluid-copy-damping: ${num(cfg.units.copy.damping)};
$fluid-copy-floor: ${num(floors.copy)};
$fluid-chrome-enabled: ${cfg.units.chrome.enabled};
$fluid-zoom-compensation: ${cfg.zoomCompensation};
$fluid-zoom-text-full: ${num(cfg.zoomTextRange[0])};
$fluid-zoom-text-none: ${num(cfg.zoomTextRange[1])};

// ── Functions ─────────────────────────────────────────────────────────
// FUNCTION AND MIXIN NAMES MOVE WITH \`prefix\` (references/contract.md §1) — the
// \`--fluid*\` CUSTOM-PROPERTY NAMES INSIDE THEM DO NOT, and are always the
// literal strings cssUnits(cfg) emits. At the default prefix these read
// identically either way, which is exactly why this bug shipped unnoticed:
// only a non-default \`prefix\` makes the two kinds of name diverge visibly.
//
// Each function returns calc(#{$n} * var(--fluid...)). $n MUST be
// unitless — the drawn number from the design file, never a length.
// \`${p}(64px)\` would build \`calc(64px * var(--fluid))\`, length times
// length, which is invalid CSS and drops the whole declaration silently.
// The @error below turns that mistake into a build failure instead.
@function _${p}-assert-unitless($n, $fn) {
  @if math.is-unitless($n) == false {
    @error "fluid-design: #{$fn}() expects a unitless drawn number, got \`#{$n}\`. \`64px * var(--fluid)\` is invalid CSS (length * length) and silently drops the declaration — pass the bare number instead.";
  }
  @return $n;
}

@function ${p}($n) {
  $n: _${p}-assert-unitless($n, '${p}');
  @return calc(#{$n} * var(--fluid));
}

@function ${p}-display($n) {
  $n: _${p}-assert-unitless($n, '${p}-display');
  @return calc(#{$n} * var(--fluid-display));
}

@function ${p}-copy($n) {
  $n: _${p}-assert-unitless($n, '${p}-copy');
  @return calc(#{$n} * var(--fluid-copy));
}

// Font size on the BASE unit, for type whose container scales with it too
// (see fluid.css's ${p}-text-* comment). Under browser zoom it takes a share
// of --fluid-zoom by size: all of it up to $fluid-zoom-text-full drawn px,
// none from $fluid-zoom-text-none, because its box does not zoom and big type
// zoomed inside it runs over its neighbours. $size is the FONT size the
// share is read from; pass it for a line-height, so the line box zooms
// exactly as its text does (${p}-type() does this for you).
@function ${p}-text($n, $size: $n) {
  $n: _${p}-assert-unitless($n, '${p}-text');
  @if not $fluid-zoom-compensation {
    @return calc(#{$n} * var(--fluid));
  }
  $w: math.clamp(0, math.div($fluid-zoom-text-none - $size, $fluid-zoom-text-none - $fluid-zoom-text-full), 1);
  @if $w == 0 {
    @return calc(#{$n} * var(--fluid));
  }
  @if $w == 1 {
    @return calc(#{$n} * var(--fluid-z));
  }
  @return calc(#{$n} * (var(--fluid) + (var(--fluid-z) - var(--fluid)) * #{$w}));
}

@function ${p}-chrome($n) {
  $n: _${p}-assert-unitless($n, '${p}-chrome');
  @return calc(#{$n} * var(--fluid-chrome));
}

// A max-width that only ever GROWS — never an ordinary max-width. See
// fluid.css's ${p}-cap-* comment for why it needs its own name.
@function ${p}-cap($n) {
  $n: _${p}-assert-unitless($n, '${p}-cap');
  @return max(#{$n}px, calc(#{$n} * var(--fluid)));
}

// ── Mixins ────────────────────────────────────────────────────────────

// The engage breakpoint, named so it never drifts from $fluid-engage-at.
@mixin ${p}-up {
  @media (width >= $fluid-engage-at) {
    @content;
  }
}

// font-size + line-height together, Tailwind's \`/lh\` modifier as a mixin.
// $unit selects which curve: display (headings), copy (small text/
// controls) or text (base unit, for type whose container scales with it).
@mixin ${p}-type($size, $lh, $unit: display) {
  @if $unit == display {
    font-size: ${p}-display($size);
    line-height: ${p}-display($lh);
  } @else if $unit == copy {
    font-size: ${p}-copy($size);
    line-height: ${p}-copy($lh);
  } @else if $unit == text {
    font-size: ${p}-text($size);
    line-height: ${p}-text($lh, $size);
  } @else {
    @error "fluid-design: ${p}-type() unit must be display, copy or text, got \`#{$unit}\`.";
  }
}

// The drawn frame as a cap + a scaled gutter, on ONE box — apply it ONCE
// PER SECTION, to that section's own single inner wrapper, never to the
// page as a whole and never stacked on a second box nested inside the same
// section (references/section-recipe.md: "the section carries full-bleed
// colour, the inner box carries the frame"). Below the engage breakpoint
// it is a plain full-width box with a fixed measure and a fixed gutter (32px
// from 640px up) — bring nothing else for mobile; the cap and the scaled
// gutter both engage together from $fluid-engage-at.
@mixin ${p}-frame {
  width: 100%;
  margin-inline: auto;
  max-width: #{$fluid-canvas-width}px;
  padding-inline: 24px;

  @media (width >= 640px) {
    padding-inline: 32px;
  }

  @include ${p}-up {
    max-width: ${p}-cap($fluid-canvas-width);
    padding-inline: ${p}($fluid-canvas-gutter);
  }
}

// Emits the :root custom-property block (flat 1px + the engaged values).
// Include it once, at :root: \`:root { @include ${p}-units; }\`
// Every declaration below is copied verbatim from cssUnits(cfg) — see the
// note at the top of this file's Functions section.
@mixin ${p}-units {
${rootLines}

  @include ${p}-up {
${engagedLines}
  }
}
`
  )
}

function buildScssReadme(cfg) {
  const p = cfg.prefix
  return (
    mdHeader(cfg, 'scss') +
    `# fluid-design — SCSS stack

\`_fluid.scss\` gives you the same scale as functions and mixins instead of
Tailwind's \`@utility\` classes.

## The \`--out\` layout and the \`@use\` path

\`node scripts/generate-fluid.mjs --stack scss --out DIR\` writes this file to
\`DIR/scss/_fluid.scss\` (the stack name is its own folder under \`DIR\`;
\`DIR/shared/base.css\` and \`DIR/scss/README.md\` land alongside it — see
\`scripts/README.md\`'s "the --out layout" for the full tree). Sass's \`@use\`
drops the leading underscore and the extension, so from a stylesheet that
can resolve \`DIR\` on its Sass \`loadPaths\` (or via a relative \`../\` path),
the import is \`@use 'scss/fluid' as fd;\` — NOT \`@use 'fluid-design/fluid'\`,
which matches neither the \`--out\` layout nor the stack subfolder. Adjust the
\`scss/\` segment if you copy the file somewhere else; the point is that the
path must name the ACTUAL folder this file was written into, not the name of
this skill.

\`\`\`scss
// e.g. with { loadPaths: ['src/styles'] } and this file copied to
// src/styles/fluid/scss/_fluid.scss:
@use 'fluid/scss/fluid' as fd;

:root {
  @include fd.${p}-units;
}

.hero {
  @include fd.${p}-up {
    padding-block: fd.${p}(120);
    @include fd.${p}-type(64, 72, $unit: display);
  }
}
\`\`\`

Apply \`fd.${p}-frame\` inside each section's own inner wrapper (never once
for the whole page, never stacked on a nested box in the same section —
references/section-recipe.md):

\`\`\`scss
.hero__inner {
  @include fd.${p}-frame;
}
\`\`\`

## Box-sizing

This stack ships no reset of its own. Include \`shared/base.css\` (or your
own equivalent) before this file — its \`*, *::before, *::after { box-sizing:
border-box }\` rule is what keeps \`${p}-frame\`'s \`max-width\` capping the
border box; without it the frame renders at canvas + 2×gutter, wider than
drawn.

## Function and mixin names move with \`prefix\`; custom properties do not

Every function/mixin above is spelled with THIS config's \`prefix\`
(\`"${p}"\`) — change \`prefix\` in \`fluid.config.json\` and regenerate to
rename all of them together. The \`--fluid*\` custom properties they read
(\`var(--fluid)\`, \`var(--fluid-display)\`, …) are fixed names and never
change with \`prefix\` (references/contract.md §1).

## The unit functions are the enforcement point

\`${p}()\`, \`${p}-display()\`, \`${p}-copy()\`, \`${p}-text()\` and
\`${p}-chrome()\` all \`@error\` if you pass a value with a unit —
\`${p}(64px)\` fails the build instead of silently compiling to
\`calc(64px * var(--fluid))\`, which is length-times-length and gets the
WHOLE declaration dropped by the browser with no warning anywhere. Sass's
build-time \`@error\` is strictly better here than CSS ever can be: it turns
a runtime rendering bug into a compile failure.

## Regenerating

Generated from \`assets/fluid.config.json\`:

\`\`\`
node scripts/generate-fluid.mjs --stack scss
\`\`\`
`
  )
}

// ── stylex ──────────────────────────────────────────────────────────────

function buildStylex(cfg) {
  const units = cssUnits(cfg)
  const unitsCss = `${rootBlock(units)}\n${engagedBlock(units)}`
  return (
    tsHeader(cfg, 'stylex') +
    `/**
 * StyleX's \`defineVars\` can only assign each variable a set of STATIC
 * strings, one per @media condition — it has no way to reference a SIBLING
 * var's generated (hashed) custom-property name from inside another var's
 * own definition, because that name does not exist until \`defineVars\`
 * returns. \`--fluid-display\`, \`--fluid-copy\` and \`--header-h\` are
 * exactly this case: each formula reads \`var(--fluid)\` (or
 * \`var(--fluid-chrome)\`) inside its own nested calc()/max()/min(). There
 * is no way to express that nesting through \`defineVars\`.
 *
 * So the units ship as a plain global stylesheet below (byte-identical in
 * shape to ../css/fluid.css, with the real custom-property names —
 * --fluid, --fluid-display, …), meant to be imported once at the app root
 * the way any other global CSS is. This file then adds typed helpers that
 * build calc() strings against those RAW names, for use as plain values in
 * your own style objects — they are not passed through defineVars, so
 * nothing here depends on StyleX being able to see inside them.
 */
import * as stylex from '@stylexjs/stylex'

export const FLUID_UNITS_CSS = \`${unitsCss.replace(/`/g, '\\`')}\`

function assertFinite(n: number, fn: string): number {
  if (!Number.isFinite(n)) {
    throw new Error(\`fluid-design: \${fn}() expects a unitless drawn number, got \${n}.\`)
  }
  return n
}

export function fluid(n: number): string {
  return \`calc(\${assertFinite(n, 'fluid')} * var(--fluid))\`
}

export function fluidDisplay(n: number): string {
  return \`calc(\${assertFinite(n, 'fluidDisplay')} * var(--fluid-display))\`
}

export function fluidCopy(n: number): string {
  return \`calc(\${assertFinite(n, 'fluidCopy')} * var(--fluid-copy))\`
}

// Font size on the BASE unit — see fluid.css's ${cfg.prefix}-text-* comment.
// Under browser zoom it takes a share of --fluid-zoom by size (all of it up
// to ${num(cfg.zoomTextRange[0])}px drawn, none from ${num(cfg.zoomTextRange[1])}px). \`size\` is the FONT size the
// share is read from: pass it for a line-height so the line box zooms with
// its text.
const ZOOM_COMPENSATION = ${cfg.zoomCompensation}
const ZOOM_TEXT_FULL = ${num(cfg.zoomTextRange[0])}
const ZOOM_TEXT_NONE = ${num(cfg.zoomTextRange[1])}
export function fluidText(n: number, size: number = n): string {
  const base = \`calc(\${assertFinite(n, 'fluidText')} * var(--fluid)\`
  if (!ZOOM_COMPENSATION) return \`\${base})\`
  const w = Math.min(1, Math.max(0, (ZOOM_TEXT_NONE - size) / (ZOOM_TEXT_NONE - ZOOM_TEXT_FULL)))
  if (w === 0) return \`\${base})\`
  if (w === 1) return \`calc(\${n} * var(--fluid-z))\`
  return \`calc(\${n} * (var(--fluid) + (var(--fluid-z) - var(--fluid)) * \${Math.round(w * 1e6) / 1e6}))\`
}

export function fluidChrome(n: number): string {
  return \`calc(\${assertFinite(n, 'fluidChrome')} * var(--fluid-chrome))\`
}

// A max-width that only ever grows — see fluid.css's ${cfg.prefix}-cap-* comment.
export function fluidCap(n: number): string {
  return \`max(\${assertFinite(n, 'fluidCap')}px, calc(\${n} * var(--fluid)))\`
}

/**
 * Leaf tokens with no cross-var reference CAN go through defineVars safely
 * — nothing inside them points back at another StyleX var.
 */
export const safeArea = stylex.defineVars({
  top: 'env(safe-area-inset-top, 0px)',
  bottom: 'env(safe-area-inset-bottom, 0px)'
})
`
  )
}

function buildStylexReadme(cfg) {
  return (
    mdHeader(cfg, 'stylex') +
    `# fluid-design — StyleX stack

StyleX cannot express \`--fluid-display\`'s formula (it reads \`var(--fluid)\`
inside its own \`calc()\`/\`max()\`) through \`defineVars\`, which only accepts
static per-\`@media\` strings and has no way to reference a sibling var's
generated name from inside another var's definition. See the docblock at
the top of \`fluid.stylex.ts\` for the full reasoning.

So this stack ships the units as plain global CSS (\`FLUID_UNITS_CSS\`,
exported as a string, or copy it to a \`.css\` file and import it) plus
typed helpers (\`fluid()\`, \`fluidDisplay()\`, \`fluidCopy()\`, \`fluidText()\`,
\`fluidChrome()\`, \`fluidCap()\`) that build \`calc()\` strings against the raw
custom-property names for use as plain values in your own \`stylex.create\`
style objects:

\`\`\`ts
import * as stylex from '@stylexjs/stylex'
import { fluid, fluidDisplay } from './fluid.stylex'

const styles = stylex.create({
  hero: {
    paddingBlock: fluid(120),
    fontSize: fluidDisplay(64)
  }
})
\`\`\`

Import \`FLUID_UNITS_CSS\` once at your app root (render it into a
\`<style>\` tag, or copy it into a real \`.css\` file and \`@import\` it — same
content either way) before any component reads \`var(--fluid...)\`.

## Regenerating

Generated from \`assets/fluid.config.json\`:

\`\`\`
node scripts/generate-fluid.mjs --stack stylex
\`\`\`
`
  )
}

// ── ts (framework-agnostic constants) ─────────────────────────────────

// The single source for the numbers this skill's own consumers need without
// a full stylesheet -- ENGAGE_PX/ENGAGE_QUERY, the reference viewport, and
// the canvas frame. If the scroll-animation skill is also installed, its
// motion ports (GSAP's `config.ts`, React's `lib/constants.ts`) each ship
// their own DEFAULT literal (1024) so they work with zero setup, but each
// carries a comment pointing back here: regenerate this file with
// `--stack ts` and import from it instead, the moment `engageAt` (or the
// reference/canvas numbers) stop matching the default.
function buildFluidConfigTs(cfg) {
  return (
    tsHeader(cfg, 'ts') +
    `/** Min-width (px) where the fluid scale turns on. Mirrors \`engageAt\` in
 * \`fluid.config.json\`. If the scroll-animation skill is also installed,
 * every hand-typed \`ENGAGE_QUERY\`/\`ENGAGE_BREAKPOINT_PX\` literal in its
 * motion ports (GSAP's \`config.ts\`, React's \`lib/constants.ts\`) should
 * import THIS constant once your config's \`engageAt\` stops matching the
 * shipped default of 1024 — see each of those files' own docblock for the
 * literal this replaces. */
export const ENGAGE_PX = ${num(cfg.engageAt)}

/** \`matchMedia\`-ready form of ENGAGE_PX. */
export const ENGAGE_QUERY = \`(min-width: \${ENGAGE_PX}px)\`

/** The viewport where every fluid unit equals exactly 1px — a content
 * budget, not the design canvas (references/fluid-scale.md §4). */
export const REFERENCE_WIDTH = ${num(cfg.reference.width)}
export const REFERENCE_HEIGHT = ${num(cfg.reference.height)}

/** The drawn design-file frame: the \`${cfg.prefix}-cap-*\` grow-only ceiling
 * width, and its page gutter. */
export const CANVAS_WIDTH = ${num(cfg.canvas.width)}
export const CANVAS_GUTTER = ${num(cfg.canvas.gutter)}
`
  )
}

// ── shared/base.css ────────────────────────────────────────────────────

function buildSharedBaseCss(cfg) {
  return (
    cssHeader(cfg, 'shared') +
    `/* Stack-agnostic base layer: box-sizing, iOS/safe-area quirks and the
   sticky/overflow trap. Include it once, after your reset/preflight, in
   every stack. Nothing here reads fluid.config.json — it has no
   config-driven numbers — but it is generated (not hand-written) so it
   stays alongside the rest of this skill's output and picks up fixes from
   one place. This is the RENDER half only: if the scroll-animation skill
   is also installed, also include its \`motion-base.css\` (scroll-behavior,
   the reduced-motion structural collapse, --fill, the noscript rules). */

/* Tailwind v4's own Preflight already sets this, so the tailwind-v4 stack
   needs nothing extra here. A non-Tailwind stack (this file, standalone, or
   the vanilla-CSS/SCSS stacks) usually has NO reset that does, and without
   it \`max-width: max(${num(cfg.canvas.width)}px, ...)\` caps the CONTENT box, not the border
   box: the frame then renders at canvas + 2×gutter (e.g. ${num(cfg.canvas.width)} + 2×${num(cfg.canvas.gutter)} =
   ${num(cfg.canvas.width + 2 * cfg.canvas.gutter)}) instead of ${num(cfg.canvas.width)}, and everything inside it overflows the intended
   frame — measured: a header CTA and the hero copy cut off at the edge. */
*,
*::before,
*::after {
  box-sizing: border-box;
}

html {
  /* Kill rubber-band / elastic overscroll. The render reason: past a
     scroll boundary an elastic bounce can pull the viewport past the
     frame canvas and reveal a gap with nothing painted in it — there is
     no content back there to show. If the scroll-animation skill is also
     installed, this also removes a source of scroll jitter for anything
     scroll-driven (a pinned scrub, a parallax track) — see its
     \`references/\`. */
  overscroll-behavior: none;
  /* The horizontal-overflow guard belongs HERE and ONLY here. See the note
     below body — putting it on body or any sticky ancestor silently kills
     position: sticky site-wide. */
  overflow-x: hidden;
}

/*
  NEVER move overflow-x: hidden onto body, or onto any ancestor of a
  position: sticky element. Measured: when one axis is set non-visible the
  OTHER axis computes to auto, so that element becomes its own scroll
  container with a scroll range of 0, while html still does the real page
  scrolling. A sticky descendant resolves its stuck position against ITS
  OWN scroll container's scrollport — which never moves — so it has no
  travel at all and behaves as position: static instead. If a component
  further down the tree needs its own horizontal clip, use \`clip\` (or
  \`clip-path\`) on that element instead of \`overflow-x\`.
*/

body {
  position: relative;
  /* NO background-color here, on purpose. iOS 26 Safari ignores
     <meta name="theme-color"> and instead derives its toolbar/status-bar
     tint by sampling the background of fixed/sticky elements near the
     viewport edges, falling back to body's background. Painting body is
     therefore not a page-content decision, it is a chrome-color decision
     that applies to every route whether or not that route wants it —
     right on a page that happens to match, wrong everywhere else. Leave
     both this and theme-color unset and let each browser default; they
     have to go together, since whichever one survives keeps steering the
     color alone. Nothing should depend on body's paint showing through —
     every section should carry its own surface, and overscroll-behavior
     above removes the rubber-band gap that would otherwise expose it. */
  min-height: -webkit-fill-available;
}

button,
a,
input,
select,
textarea {
  touch-action: manipulation;
  -webkit-tap-highlight-color: transparent;
}

/* Modern CSS resets (Tailwind v4 Preflight included) often drop
   cursor: pointer on <button>; restore it site-wide for interactive
   elements if yours does too. */
button:not(:disabled),
[role='button']:not([aria-disabled='true']),
summary {
  cursor: pointer;
}
button:disabled {
  cursor: not-allowed;
}

/* --focus-ring is a TOKEN, not a hard-coded color — define it in your own
   theme (tailwind-v4/tokens.example.css shows the alias). The fallback
   keeps this file usable standalone. */
:focus-visible {
  outline: 2px solid var(--focus-ring, #2563eb);
  outline-offset: 2px;
}
:focus:not(:focus-visible) {
  outline: none;
}

/*
  video { max-width: none } — documented here as a COMMENT, not shipped as
  a rule, because it must never be global. Most CSS resets (Tailwind
  Preflight included) cap \`video { max-width: 100% }\`, which silently
  clamps a full-bleed video to its container's width. Undo it on the
  SPECIFIC element that needs to bleed past its container (a utility
  class, or an id/data-attribute rule scoped to that one video) — a
  blanket override reintroduces exactly the overflow the reset existed to
  prevent, everywhere else on the site.
*/
`
  )
}

// ── CLI ─────────────────────────────────────────────────────────────────

const USAGE = `generate-fluid.mjs — deterministic generator for every fluid-design style stack.

Usage:
  node generate-fluid.mjs [--config fluid.config.json] --stack tailwind-v4|css|scss|stylex|ts|all [--out DIR] [--check]

Options:
  --config <file>   config file to load instead of the shipped defaults (assets/fluid.config.json)
  --stack <name>    which stack to write: tailwind-v4, css, scss, stylex, ts, or all (default: all)
  --out <dir>       output directory (default: assets/styles, relative to the skill root)
  --check           regenerate from the DEFAULT config plus every fixture config under
                     scripts/fixtures/configs/, diff against what's on disk, write nothing,
                     exit 1 if anything differs
  -h, --help        print this message and exit

The --out layout: each stack writes into its OWN subfolder, "<out>/<stack>/...":
  <out>/tailwind-v4/fluid.css, tokens.example.css, cn.ts, README.md
  <out>/css/fluid.css, README.md
  <out>/scss/_fluid.scss, README.md
  <out>/stylex/fluid.stylex.ts, README.md
  <out>/ts/fluid.config.ts
  <out>/shared/base.css                          (always written, every run, any --stack)

The committed assets/styles/* tree is exactly this script's output for the default
config (assets/fluid.config.json) with --out assets/styles — never hand-edit it;
edit the config (or this generator) and re-run.

Exit codes: 0 ok, 1 --check found a difference, 2 usage/invocation error.`

function parseArgs(argv) {
  const args = { stack: null, config: undefined, out: DEFAULT_OUT_DIR, check: false }
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a === '--config') args.config = argv[++i]
    else if (a === '--stack') args.stack = argv[++i]
    else if (a === '--out') args.out = resolvePath(argv[++i])
    else if (a === '--check') args.check = true
    else throw new Error(`unrecognised argument "${a}"`)
  }
  return args
}

function stacksToBuild(stack) {
  if (stack === 'all' || stack == null) return STACKS
  if (!STACKS.includes(stack)) {
    throw new Error(`unknown --stack "${stack}", expected one of: ${STACKS.join(', ')}, all`)
  }
  return [stack]
}

function buildFiles(cfg, stacks) {
  /** @type {Record<string, string>} */
  const files = {}
  if (stacks.includes('tailwind-v4')) {
    files['tailwind-v4/fluid.css'] = buildTailwindFluidCss(cfg)
    files['tailwind-v4/tokens.example.css'] = buildTokensExampleCss(cfg)
    files['tailwind-v4/cn.ts'] = buildCnTs(cfg)
    files['tailwind-v4/README.md'] = buildTailwindReadme(cfg)
  }
  if (stacks.includes('css')) {
    files['css/fluid.css'] = buildVanillaCss(cfg)
    files['css/README.md'] = buildVanillaReadme(cfg)
  }
  if (stacks.includes('scss')) {
    files['scss/_fluid.scss'] = buildScss(cfg)
    files['scss/README.md'] = buildScssReadme(cfg)
  }
  if (stacks.includes('stylex')) {
    files['stylex/fluid.stylex.ts'] = buildStylex(cfg)
    files['stylex/README.md'] = buildStylexReadme(cfg)
  }
  if (stacks.includes('ts')) {
    files['ts/fluid.config.ts'] = buildFluidConfigTs(cfg)
  }
  // Every stack README ends with the same browser-zoom install note, so no
  // stack's instructions can silently leave the runtime out.
  for (const rel of Object.keys(files)) {
    if (rel.endsWith('/README.md')) files[rel] = files[rel].replace(/\n*$/, '\n') + zoomReadmeNote(cfg)
  }
  // shared/base.css is stack-agnostic and always (re)generated, regardless
  // of which stack(s) were requested.
  files['shared/base.css'] = buildSharedBaseCss(cfg)
  return files
}

function zoomReadmeNote(cfg) {
  if (!cfg.zoomCompensation) {
    return `
## Browser zoom

\`zoomCompensation\` is off in this config, so the type units ignore browser
zoom from the engage breakpoint up: vw/svh-derived type renders at the same
physical size at every zoom level, a WCAG 1.4.4 failure on wide displays.
That should be a recorded, informed decision (references/fluid-scale.md §12).
`
  }
  return `
## Browser zoom

The type units read \`var(--fluid-zoom, 1)\`, which
\`assets/runtime/fluid-zoom.js\` sets to the detected browser zoom. Without
it, type does not grow under Cmd/Ctrl + on wide displays (WCAG 1.4.4). Copy
\`fluid-zoom.js\` and \`fluid-zoom.d.ts\` into the project and inline it in
\`<head>\`, before first paint:

\`\`\`tsx
import { FLUID_ZOOM_INLINE } from './fluid-zoom.js'
// <head>
<script dangerouslySetInnerHTML={{ __html: FLUID_ZOOM_INLINE }} />
\`\`\`

Without React, put the string in a plain \`<script>\` in \`<head>\`, or call
\`installFluidZoom()\` as early as your entry allows. Check it with
\`verify-matrix.mjs\`'s zoom row (references/fluid-scale.md §12).
`
}

// The last `--fluid:` declaration in a stack's unit output — the root block
// always writes the flat `--fluid: 1px;` first, so the LAST match is always
// the engaged (real) expression, in every stack's syntax: plain CSS
// (tailwind-v4, css), a mixin body (scss — cssUnits(cfg)'s engaged strings
// are emitted verbatim, see buildScss), or the raw CSS text embedded in
// stylex's FLUID_UNITS_CSS template string.
function extractFluidExpr(content) {
  const matches = [...content.matchAll(/--fluid:\s*([^;]+);/g)]
  if (matches.length === 0) return null
  return matches[matches.length - 1][1].trim()
}

// Cross-stack invariants that hold for ANY config, checked against files
// built in-memory (never diffed against disk — only the default config has
// a committed tree to diff against). This is what actually catches #1/#2's
// class of bug: the SCSS emitter's old hand-written --fluid ignored
// `ceiling` entirely and built the literal string `--fluid-fluid` when
// chrome was disabled, and the DEFAULT config (ceiling: null, chrome
// enabled) cannot exercise either path — a fixture config has to.
function checkFixtureInvariants(cfg, files, label, mismatches) {
  const unitFiles = ['tailwind-v4/fluid.css', 'css/fluid.css', 'scss/_fluid.scss', 'stylex/fluid.stylex.ts']
  const exprs = new Map()
  for (const rel of unitFiles) {
    const content = files[rel]
    if (!content) continue
    if (content.includes('var(--fluid-fluid)')) {
      mismatches.push(`${label}: ${rel} emits var(--fluid-fluid) — a stack-local expression diverged from cssUnits(cfg)`)
    }
    if (cfg.ceiling !== null && !content.includes(`min(${num(cfg.ceiling)}px`)) {
      mismatches.push(`${label}: ${rel} has no min(${num(cfg.ceiling)}px — ceiling is set but this stack does not cap --fluid`)
    }
    // The engaged --fluid-display declaration (the last one; the root block
    // writes `1px` first) must read the zoom factor exactly when configured.
    // Function bodies (scss, stylex) mention var(--fluid-zoom) either way,
    // behind a compile-time switch, so only the declaration is conclusive.
    const displayDecls = [...content.matchAll(/--fluid-display:\s*([^;]+);/g)]
    const displayExpr = displayDecls.length ? displayDecls[displayDecls.length - 1][1] : ''
    const zoomed = displayExpr.includes('var(--fluid-z)') && /--fluid-z:\s*[^;]*var\(--fluid-zoom, 1\)/.test(content)
    if (cfg.zoomCompensation !== zoomed) {
      mismatches.push(`${label}: ${rel} --fluid-display ${zoomed ? 'reads' : 'does not read'} a zoom-compensated --fluid-z but zoomCompensation is ${cfg.zoomCompensation}`)
    }
    const expr = extractFluidExpr(content)
    if (expr === null) {
      mismatches.push(`${label}: ${rel} has no --fluid: declaration to compare`)
      continue
    }
    exprs.set(rel, expr)
  }
  const distinct = new Set(exprs.values())
  if (distinct.size > 1) {
    mismatches.push(`${label}: --fluid expression differs across stacks — ${[...exprs.entries()].map(([k, v]) => `${k}: ${v}`).join('  |  ')}`)
  }
}

function main() {
  const argv = process.argv.slice(2)
  if (argv.includes('--help') || argv.includes('-h')) {
    console.log(USAGE)
    process.exit(0)
  }
  const args = parseArgs(argv)

  if (args.check) {
    const mismatches = []

    const cfg = loadConfig(DEFAULT_CONFIG_PATH)
    const files = buildFiles(cfg, STACKS)
    for (const [rel, expected] of Object.entries(files)) {
      const abs = join(DEFAULT_OUT_DIR, rel)
      if (!existsSync(abs)) {
        mismatches.push(`missing: ${rel}`)
        continue
      }
      const actual = readFileSync(abs, 'utf8')
      if (actual !== expected) {
        mismatches.push(`stale: ${rel}`)
      }
    }
    checkFixtureInvariants(cfg, files, 'default config', mismatches)

    // Fixture configs (scripts/fixtures/configs/*.json) are generated
    // in-memory only — there is no committed disk tree to diff them
    // against, so they are checked against the invariants above instead.
    let fixtureNames = []
    try {
      fixtureNames = readdirSync(FIXTURE_CONFIGS_DIR)
        .filter((f) => f.endsWith('.json'))
        .sort()
    } catch {
      // no fixtures directory: nothing to run, defaults-only check above stands
    }
    for (const name of fixtureNames) {
      const fixtureCfg = loadConfig(join(FIXTURE_CONFIGS_DIR, name))
      const fixtureFiles = buildFiles(fixtureCfg, STACKS)
      checkFixtureInvariants(fixtureCfg, fixtureFiles, `fixture ${name}`, mismatches)
    }

    if (mismatches.length > 0) {
      console.error('[fluid-design] --check found differences:')
      for (const m of mismatches) console.error(`  ${m}`)
      console.error('Run: node scripts/generate-fluid.mjs --stack all')
      process.exit(1)
    }
    console.log(`[fluid-design] --check OK — assets/styles matches the default config, and ${fixtureNames.length} fixture config(s) (${fixtureNames.join(', ') || 'none'}) pass the cross-stack invariants.`)
    return
  }

  const cfg = loadConfig(args.config)
  const stacks = stacksToBuild(args.stack)
  const files = buildFiles(cfg, stacks)

  for (const [rel, content] of Object.entries(files)) {
    const abs = join(args.out, rel)
    mkdirSync(dirname(abs), { recursive: true })
    writeFileSync(abs, content)
  }

  console.log(`[fluid-design] wrote ${Object.keys(files).length} file(s) to ${args.out}`)
}

main()
