/**
 * GENERATED by fluid-design's generate-fluid.mjs — do not hand-edit.
 * Edit fluid.config.json and re-run:
 *   node scripts/generate-fluid.mjs --stack tailwind-v4
 * 
 * Config:
 *   reference 1440x900, canvas 1680/80, engageAt 1024, heightAxis true
 *   fluid.floor 0.58
 *   display.damping 0.62 (floor auto -> 0.82)
 *   copy.damping 0.33 (floor auto -> 0.9)
 *   chrome.enabled true
 *   ceiling none
 *   prefix "fluid"
 */

import { type ClassValue, clsx } from 'clsx'
import { extendTailwindMerge } from 'tailwind-merge'

/**
 * `tailwind-merge` resolves conflicts from a table of class groups it ships
 * with. `fluid-*` utilities are not in that table, so out of the box it
 * treats every one of them as an unknown class and keeps ALL of them:
 *
 *   twMerge('lg:fluid-p-40 lg:fluid-p-24')  ->  BOTH survive
 *   twMerge('lg:w-[380px] lg:fluid-w-560') ->  BOTH survive
 *
 * Two declarations of the same property then both reach the browser, and
 * CSS SOURCE ORDER decides which wins — not the order they were written in
 * the class string. That is the opposite of what every caller assumes when
 * they pass `className` to override a component's default, and it stays
 * invisible right up until a shared component starts accepting
 * `className` on top of its own fluid classes.
 *
 * So each family is registered into the Tailwind class group its property
 * already belongs to: `fluid-p-*` joins `p`, `fluid-w-*` joins `w`, and all
 * three font-size families join `font-size`, which additionally makes
 * them conflict with EACH OTHER — `fluid-text-14 fluid-copy-14` then
 * resolves to the last one instead of shipping two font sizes.
 */

// Every fluid utility takes a bare number, optionally with Tailwind's `/`
// line-height modifier: `fluid-p-40`, `fluid-text-14`, `fluid-text-14/18`.
// Decimals are allowed — the scale accepts any drawn number.
const isFluidValue = (value: string) => /^\d+(\.\d+)?(\/\d+(\.\d+)?)?$/.test(value)

const fluid = (name: string) => ({ [name]: [isFluidValue] })

export const twMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      // Spacing
      p: [fluid('fluid-p')],
      px: [fluid('fluid-px')],
      py: [fluid('fluid-py')],
      pt: [fluid('fluid-pt')],
      pb: [fluid('fluid-pb')],
      pl: [fluid('fluid-pl')],
      pr: [fluid('fluid-pr')],
      m: [fluid('fluid-m')],
      mx: [fluid('fluid-mx')],
      my: [fluid('fluid-my')],
      mt: [fluid('fluid-mt')],
      mb: [fluid('fluid-mb')],
      ml: [fluid('fluid-ml')],
      mr: [fluid('fluid-mr')],
      gap: [fluid('fluid-gap')],
      'gap-x': [fluid('fluid-gap-x')],
      'gap-y': [fluid('fluid-gap-y')],

      // Box
      w: [fluid('fluid-w')],
      h: [fluid('fluid-h')],
      size: [fluid('fluid-size')],
      'min-w': [fluid('fluid-min-w')],
      'min-h': [fluid('fluid-min-h')],
      'max-h': [fluid('fluid-max-h')],
      // `fluid-cap-*` IS a max-width, however differently it behaves (it
      // only ever grows). A plain `max-w-*` next to it is still a conflict.
      'max-w': [fluid('fluid-cap')],

      // Type — all three land in ONE group on purpose: they are three
      // units for one property, so two of them on one element is always a
      // mistake, never an intentional pair.
      'font-size': [fluid('fluid-text'), fluid('fluid-copy'), fluid('fluid-display')],

      // Position
      inset: [fluid('fluid-inset')],
      top: [fluid('fluid-top')],
      right: [fluid('fluid-right')],
      bottom: [fluid('fluid-bottom')],
      left: [fluid('fluid-left')],

      'translate-x': [fluid('fluid-translate-x')],
      'translate-y': [fluid('fluid-translate-y')]
    }
  }
})

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
