/**
 * GENERATED by fluid-design's generate-fluid.mjs — do not hand-edit.
 * Edit fluid.config.json and re-run:
 *   node scripts/generate-fluid.mjs --stack stylex
 * 
 * Config:
 *   reference 1440x900, canvas 1680/80, engageAt 1024, heightAxis true
 *   fluid.floor 0.58
 *   display.damping 0.62 (floor auto -> 0.82)
 *   copy.damping 0.33 (floor auto -> 0.9)
 *   chrome.enabled true
 *   ceiling none
 *   zoomCompensation true
 *   prefix "fluid"
 */

/**
 * StyleX's `defineVars` can only assign each variable a set of STATIC
 * strings, one per @media condition — it has no way to reference a SIBLING
 * var's generated (hashed) custom-property name from inside another var's
 * own definition, because that name does not exist until `defineVars`
 * returns. `--fluid-display`, `--fluid-copy` and `--header-h` are
 * exactly this case: each formula reads `var(--fluid)` (or
 * `var(--fluid-chrome)`) inside its own nested calc()/max()/min(). There
 * is no way to express that nesting through `defineVars`.
 *
 * So the units ship as a plain global stylesheet below (byte-identical in
 * shape to ../css/fluid.css, with the real custom-property names —
 * --fluid, --fluid-display, …), meant to be imported once at the app root
 * the way any other global CSS is. This file then adds typed helpers that
 * build calc() strings against those RAW names, for use as plain values in
 * your own style objects — they are not passed through defineVars, so
 * nothing here depends on StyleX being able to see inside them.
 */
import * as stylex from '@stylexjs/stylex'

export const FLUID_UNITS_CSS = `:root {
  --fluid: 1px;
  --fluid-display: 1px;
  --fluid-copy: 1px;
  --fluid-chrome: 1px;
  --safe-top: env(safe-area-inset-top, 0px);
  --safe-bottom: env(safe-area-inset-bottom, 0px);
  --browser-bar: calc(100lvh - 100svh);
  --header-h: calc(24 * var(--fluid) + var(--safe-top) + 34px);
}

@media (width >= 1024px) {
  :root {
    --fluid: max(0.58px, min(calc(100svh / 900), calc(100vw / 1440)));
    --fluid-display: max(0.82px, calc(var(--fluid) * var(--fluid-zoom, 1)), calc(0.62 * calc(var(--fluid) * var(--fluid-zoom, 1)) + 0.38px));
    --fluid-copy: max(0.9px, calc(var(--fluid) * var(--fluid-zoom, 1)), calc(0.33 * calc(var(--fluid) * var(--fluid-zoom, 1)) + 0.67px));
    --fluid-chrome: min(calc(100vw / 1440), max(1px, calc(100svh / 900)));
    --header-h: calc(24 * var(--fluid) + var(--safe-top) + 48 * var(--fluid-chrome));
  }
}
`

function assertFinite(n: number, fn: string): number {
  if (!Number.isFinite(n)) {
    throw new Error(`fluid-design: ${fn}() expects a unitless drawn number, got ${n}.`)
  }
  return n
}

export function fluid(n: number): string {
  return `calc(${assertFinite(n, 'fluid')} * var(--fluid))`
}

export function fluidDisplay(n: number): string {
  return `calc(${assertFinite(n, 'fluidDisplay')} * var(--fluid-display))`
}

export function fluidCopy(n: number): string {
  return `calc(${assertFinite(n, 'fluidCopy')} * var(--fluid-copy))`
}

// Font size on the BASE unit — see fluid.css's fluid-text-* comment.
export function fluidText(n: number): string {
  return `calc(${assertFinite(n, 'fluidText')} * var(--fluid))`
}

export function fluidChrome(n: number): string {
  return `calc(${assertFinite(n, 'fluidChrome')} * var(--fluid-chrome))`
}

// A max-width that only ever grows — see fluid.css's fluid-cap-* comment.
export function fluidCap(n: number): string {
  return `max(${assertFinite(n, 'fluidCap')}px, calc(${n} * var(--fluid)))`
}

/**
 * Leaf tokens with no cross-var reference CAN go through defineVars safely
 * — nothing inside them points back at another StyleX var.
 */
export const safeArea = stylex.defineVars({
  top: 'env(safe-area-inset-top, 0px)',
  bottom: 'env(safe-area-inset-bottom, 0px)'
})
