/**
 * GENERATED by fluid-design's generate-fluid.mjs — do not hand-edit.
 * Edit fluid.config.json and re-run:
 *   node scripts/generate-fluid.mjs --stack stylex
 * 
 * Config:
 *   reference 1440x900, canvas 1680/80, engageAt 1024, heightAxis true
 *   fluid.floor 0.58
 *   display.damping 0.62 (floor auto -> 0.82)
 *   copy.damping 0.33 (floor auto -> 0.9)
 *   chrome.enabled true
 *   ceiling none
 *   zoomCompensation true (fluid-text: full <= 24, none >= 48)
 *   prefix "fluid"
 */

/**
 * StyleX's `defineVars` can only assign each variable a set of STATIC
 * strings, one per @media condition — it has no way to reference a SIBLING
 * var's generated (hashed) custom-property name from inside another var's
 * own definition, because that name does not exist until `defineVars`
 * returns. `--fluid-display`, `--fluid-copy` and `--header-h` are
 * exactly this case: each formula reads `var(--fluid)` (or
 * `var(--fluid-chrome)`) inside its own nested calc()/max()/min(). There
 * is no way to express that nesting through `defineVars`.
 *
 * So the units ship as a plain global stylesheet below (byte-identical in
 * shape to ../css/fluid.css, with the real custom-property names —
 * --fluid, --fluid-display, …), meant to be imported once at the app root
 * the way any other global CSS is. This file then adds typed helpers that
 * build calc() strings against those RAW names, for use as plain values in
 * your own style objects — they are not passed through defineVars, so
 * nothing here depends on StyleX being able to see inside them.
 */
import * as stylex from '@stylexjs/stylex'

export const FLUID_UNITS_CSS = `:root {
  --fluid: 1px;
  --fluid-z: 1px;
  --fluid-display: 1px;
  --fluid-copy: 1px;
  --fluid-chrome: 1px;
  --safe-top: env(safe-area-inset-top, 0px);
  --safe-bottom: env(safe-area-inset-bottom, 0px);
  --browser-bar: calc(100lvh - 100svh);
  --header-h: calc(24 * var(--fluid) + var(--safe-top) + 34px);
}

@media (width >= 1024px) {
  :root {
    --fluid: calc(max(580px, min(calc(100svh * 1000 / 900), calc(100vw * 1000 / 1440))) / 1000);
    --fluid-z: calc(max(580px, min(calc(100svh * 1000 / 900 * var(--fluid-zoom, 1)), calc(100vw * 1000 / 1440 * var(--fluid-zoom, 1)))) / 1000);
    --fluid-display: calc(max(820px, calc(var(--fluid-z) * 1000), calc(620 * var(--fluid-z) + 380px)) / 1000);
    --fluid-copy: calc(max(900px, calc(var(--fluid-z) * 1000), calc(330 * var(--fluid-z) + 670px)) / 1000);
    --fluid-chrome: calc(min(calc(100vw * 1000 / 1440), max(1000px, calc(100svh * 1000 / 900))) / 1000);
    --header-h: calc(24 * var(--fluid) + var(--safe-top) + 48 * var(--fluid-chrome));
  }
}
`

function assertFinite(n: number, fn: string): number {
  if (!Number.isFinite(n)) {
    throw new Error(`fluid-design: ${fn}() expects a unitless drawn number, got ${n}.`)
  }
  return n
}

export function fluid(n: number): string {
  return `calc(${assertFinite(n, 'fluid')} * var(--fluid))`
}

export function fluidDisplay(n: number): string {
  return `calc(${assertFinite(n, 'fluidDisplay')} * var(--fluid-display))`
}

export function fluidCopy(n: number): string {
  return `calc(${assertFinite(n, 'fluidCopy')} * var(--fluid-copy))`
}

// Font size on the BASE unit — see fluid.css's fluid-text-* comment.
// Under browser zoom it takes a share of --fluid-zoom by size (all of it up
// to 24px drawn, none from 48px). `size` is the FONT size the
// share is read from: pass it for a line-height so the line box zooms with
// its text.
const ZOOM_COMPENSATION = true
const ZOOM_TEXT_FULL = 24
const ZOOM_TEXT_NONE = 48
export function fluidText(n: number, size: number = n): string {
  const base = `calc(${assertFinite(n, 'fluidText')} * var(--fluid)`
  if (!ZOOM_COMPENSATION) return `${base})`
  const w = Math.min(1, Math.max(0, (ZOOM_TEXT_NONE - size) / (ZOOM_TEXT_NONE - ZOOM_TEXT_FULL)))
  if (w === 0) return `${base})`
  if (w === 1) return `calc(${n} * var(--fluid-z))`
  return `calc(${n} * (var(--fluid) + (var(--fluid-z) - var(--fluid)) * ${Math.round(w * 1e6) / 1e6}))`
}

export function fluidChrome(n: number): string {
  return `calc(${assertFinite(n, 'fluidChrome')} * var(--fluid-chrome))`
}

// A max-width that only ever grows — see fluid.css's fluid-cap-* comment.
export function fluidCap(n: number): string {
  return `max(${assertFinite(n, 'fluidCap')}px, calc(${n} * var(--fluid)))`
}

/**
 * Leaf tokens with no cross-var reference CAN go through defineVars safely
 * — nothing inside them points back at another StyleX var.
 */
export const safeArea = stylex.defineVars({
  top: 'env(safe-area-inset-top, 0px)',
  bottom: 'env(safe-area-inset-bottom, 0px)'
})
