// check.mjs — fluid check [--verbose]: the CI gate.

import { readFileSync } from 'node:fs'
import { relative } from 'node:path'
import { SKILL_VERSION } from '../../lib/spec.mjs'
import { readJson, isV1 } from '../../lib/model.mjs'
import { buildOutput } from '../../lib/emit/project.mjs'
import { scanProject, projectStyleFiles } from '../../lib/settings.mjs'
import { c, fail } from '../ui.mjs'
import { LOCK, findConfig, project, diffOutput, formatterHint } from '../project.mjs'

export async function cmdCheck(flags) {
  const path = findConfig(flags)
  if (!path) fail(`No fluid.config.json found here or above. Start with ${c.bold('fluid init')}.`, 2)
  const json = readJson(path)
  if (isV1(json)) fail(`${c.red('✗')} fluid.config.json is v1. Run ${c.bold('fluid migrate --write')}.`, 1)
  const p = project(flags)
  let errors = 0
  let warns = 0

  // 1. generated files
  const { files } = buildOutput(p.structure)
  const { rows, lock } = diffOutput(p.outDir, files)
  // A formatter's rewrite and a kept orphan are warnings; the rest fail.
  const soft = new Set(['reformatted', 'orphan-edited'])
  const bad = rows.filter((r) => r.state !== 'ok')
  // Two versions of the CLI (a teammate's binary, CI's npx) generate
  // different stamps: name it, instead of a list of "stale" files.
  if (lock?.generator && lock.generator !== `fluid-design ${SKILL_VERSION}`) {
    console.log(`${c.yellow('!')} ${relative(process.cwd(), p.outDir)} was generated by ${lock.generator}; this is fluid-design ${SKILL_VERSION}. Pin one version (npx fluid-design-cli@<version>, or the same binary) across the team and CI, or run ${c.bold('fluid generate')} with this one.`)
    warns++
  }
  if (bad.length) {
    errors += bad.filter((r) => !soft.has(r.state)).length
    warns += bad.filter((r) => soft.has(r.state)).length
    console.log(`${c.red('✗')} generated files are out of date (${relative(process.cwd(), p.outDir)}):`)
    for (const r of bad) {
      const why = { missing: 'missing', stale: 'config or CLI version changed since the last generate', reformatted: `reformatted by a formatter (${formatterHint(p)})`, 'hand-edited': 'edited by hand (it will be overwritten)', unowned: `differs, and there is no ${LOCK} to tell whether by hand`, orphan: 'no longer generated', 'orphan-edited': 'no longer generated, and edited since (generate keeps it)' }[r.state]
      console.log(`    ${r.rel} — ${why}`)
    }
    console.log(`  run ${c.bold('fluid generate')}${bad.some((r) => r.state === 'hand-edited') ? ' (after moving hand edits into a setting)' : ''}`)
  } else console.log(`${c.green('✓')} generated files match fluid.config.json`)

  // 2. settings (info notes, like "your own --fluid-space-s token", only with --verbose)
  const { findings } = scanProject(p.structure, p.dir, p.outDir)
  let infos = 0
  for (const f of findings) {
    if (f.level === 'info') infos++
    if (f.level === 'info' && !flags.verbose) continue
    const tag = f.level === 'error' ? c.red('✗') : f.level === 'warn' ? c.yellow('!') : c.dim('i')
    console.log(`${tag} ${f.file}:${f.line} ${f.message}`)
    if (f.level === 'error') errors++
    if (f.level === 'warn') warns++
  }
  if (findings.length === infos) console.log(`${c.green('✓')} settings: nothing to flag${infos ? c.dim(` (${infos} note(s): fluid check --verbose)`) : ''}`)

  // 3. Source rules (the audit's, self-tested): a limit on <header>, a
  //    tailwind-merge without withFluid, band variants mixed with
  //    breakpoints, the removed fluid-desktop:, limits on children,
  //    line-height modifiers that read as ratios.
  const { runAudit, CHECK_RULES } = await import('../../tools/audit.mjs')
  const audit = runAudit({ root: p.dir, prefix: p.structure.prefix, desktopVariant: 'lg', roles: p.structure.roles, stack: p.structure.output.stack, outDir: p.outDir, rules: CHECK_RULES })
  for (const f of audit) {
    if (f.severity === 'info' && !flags.verbose) continue
    const tag = f.severity === 'error' ? c.red('✗') : f.severity === 'warn' ? c.yellow('!') : c.dim('i')
    console.log(`${tag} ${f.rel}:${f.line} ${f.why} ${c.dim(f.fix)}`)
    if (f.severity === 'error') errors++
    if (f.severity === 'warn') warns++
  }

  // 4. The px breakpoint ladder replaces @theme's; a rung you declare too
  //    (a rem md: sorts after the px 2xl:) reorders the variants.
  if (p.structure.output.stack === 'tailwind-v4' && p.structure.tailwind.breakpoints === 'ladder') {
    for (const f of projectStyleFiles(p.dir, p.outDir)) {
      const text = readFileSync(f, 'utf8')
      for (const m of text.matchAll(/--breakpoint-([\w-]+)\s*:\s*([^;]+);/g)) {
        errors++
        const line = text.slice(0, m.index).split('\n').length
        console.log(`${c.red('✗')} ${relative(p.dir, f)}:${line} --breakpoint-${m[1]}: ${m[2].trim()} competes with the fluid px ladder (fluid.css sets sm-2xl, lg = the desktop band). Remove it, or set "tailwind": { "breakpoints": "none" } in fluid.config.json and keep your own (lg must then be ${p.structure.bands.desktop.minWidth}px).`)
      }
    }
  }

  // 5. breakpoints you manage yourself must agree with the bands
  if (p.structure.output.stack === 'tailwind-v4' && p.structure.tailwind.breakpoints === 'none') {
    for (const f of projectStyleFiles(p.dir, p.outDir)) {
      const m = /--breakpoint-lg\s*:\s*([\d.]+)(px|rem)/.exec(readFileSync(f, 'utf8'))
      if (m && !(m[2] === 'px' && Number(m[1]) === p.structure.bands.desktop.minWidth)) {
        errors++
        console.log(`${c.red('✗')} ${relative(p.dir, f)}: --breakpoint-lg is ${m[1]}${m[2]}, but the desktop band starts at ${p.structure.bands.desktop.minWidth}px — lg: and the units would switch at different widths`)
      }
    }
  }
  console.log(errors ? c.red(`${errors} problem(s)`) : c.green('OK') + (warns ? c.yellow(` (${warns} warning(s))`) : ''))
  process.exitCode = errors ? 1 : 0
}
