// readme.mjs — the generated README in output.dir: how to use what is in
// this folder, and the reasoning the CSS no longer carries as comments.

import { SKILL_VERSION, bandBlurb } from '../spec.mjs'
import { exclusiveMedia } from '../model.mjs'

export function readmeMd(structure, fileList) {
  const p = structure.prefix
  const stack = structure.output.stack
  const tw = stack === 'tailwind-v4'
  const ex = exclusiveMedia(structure)
  const bands = ['phone', 'tablet', 'landscape', 'desktop'].filter((b) => ex[b])
  const roles = structure.roles
  const imp = tw
    ? `@import 'tailwindcss';\n@import './fluid/fluid.css';`
    : stack === 'scss'
      ? `/* main.ts (or any global CSS) */\nimport './styles/fluid/fluid.css'\n\n// any .scss file (with the folder that holds fluid/ on Sass loadPaths)\n@use 'fluid' as fd;`
      : `@import './fluid/fluid.css';`
  return `<!-- fluid-design ${SKILL_VERSION} · GENERATED — do not edit. Run \`fluid generate\`. -->

# fluid

Generated by fluid-design from \`fluid.config.json\`. Nothing in this folder is
hand-edited: change the config and run \`fluid generate\`, or change a setting
(below) with no regenerate at all.

## Install

${'```css'}
${imp}
${'```'}

${tw ? `That one import brings the units, the settings, the base layer${structure.output.base ? '' : ' (off: output.base is false)'}, the breakpoints,
the band variants and every \`${p}-*\` utility.` : 'That one import brings the units, the settings and the base layer.'}
${structure.zoom ? `
Browser zoom needs one script in \`<head>\`, before first paint:
${structure.output.integration === 'next' ? `
${'```tsx'}
// app/layout.tsx
import { FluidHead } from '@/styles/fluid/integrations/next'
<html><head><FluidHead /></head>…
${'```'}` : structure.output.integration === 'vite' ? `
${'```ts'}
// vite.config.ts
import { fluidPlugin } from './src/styles/fluid/integrations/vite'
export default defineConfig({ plugins: [fluidPlugin()] })
${'```'}` : `
${'```html'}
<!-- first thing in <head>; a classic script, not type="module" -->
<script src="/…/runtime/zoom.classic.js"></script>
${'```'}
(or paste runtime/zoom.classic.js inline in that <script>.)
(\`output.integration\` can generate this for Next or Vite.)`}
` : ''}
## Tuning: settings are CSS variables

Every number you tune is a CSS variable with a registered default. Set the
ones you want to change in your own \`:root\`, next to your tokens:

${'```css'}
:root {
  --fluid-phone-scale-min: 0.8;
  --fluid-desktop-display-damping: 0.7;
}
${'```'}

\`settings.reference.css\` lists every one with its default and what it does.
Order does not matter, an invalid value falls back to the default, and
changes apply live. \`fluid check\` lints them, \`fluid explain 390x844\` shows
what everything resolves to at a viewport and where each value came from.

## Bands

${bands.map((b) => `- **${b}** — ${bandBlurb(structure, b)}. \`${ex[b]}\``).join('\n')}

Authors write each drawing once: the phone numbers for every mobile band,
the desktop numbers from \`lg:\` up. Only the unit changes between bands.

## Units

| Unit | Use it for |
|---|---|
| \`--fluid\` | layout: spacing, sizes, positions (\`${p}-p-*\`, \`${p}-w-*\`, …) |
${roles.map((r) => `| \`--fluid-${r}\` | ${r} type (\`${p}-${r}-64/72\`): damped, so it shrinks less than the layout |`).join('\n')}
| \`--fluid-text\` (via \`${p}-text-*\`) | type inside a box that scales with the layout |
${structure.ui ? `| \`--fluid-ui\` | the header, nav, footer: follows the width, never shrinks for a short window (\`${p}-ui-h-*\`, …) |\n` : ''}| \`--fluid-container-width\` / \`-padding\` | the page container (\`${p}-container\`) |
| \`--header-h\` | the header's height, safe area included |

Scripts read the same units as numbers: \`fluidPx(600)\`, \`fluidPx(24, '${roles[1] ?? roles[0]}')\` (from \`fluid.ts\`).

## Why it is built this way

- **One scale per band, no per-section re-anchoring.** A section drawn taller
  than the artboard is more than one screen at every viewport.
- **min() of the two desktop axes** (fit, not cover): a section drawn as tall
  as the artboard never outgrows the window. svh, not dvh, so type does not
  resize mid-scroll when a mobile toolbar collapses.
- **Damped type**: a heading shares its column with fixed measures, so it
  rides a gentler curve than the layout. Below the desktop band's edge the
  damping is read at the edge (the "knee"), which is what holds headings up
  on a short window.
- **×1000 precision**: every comparison runs on lengths scaled by 1000 and
  divides once, because Firefox rounds a min()/max() result to 1/60 px.
- **Unitless numbers**: \`calc(64 * var(--fluid))\`, never \`64px * var(--fluid)\`
  (length × length is invalid and the browser drops it silently).
- **Not scaled on purpose**: border widths, \`tracking-*\` (use em), fixed text
  measures.

## Files

${fileList.map((f) => `- \`${f}\``).join('\n')}
`
}
