#!/usr/bin/env node
// generate-fluid.mjs — the SKILL's own generator (projects use `fluid generate`).
//
// Writes everything in this skill that is derived from spec.mjs, so none of
// it can drift from the one source:
//
//   assets/fluid.config.json          the example config: every structure key, at its default
//   assets/fluid.config.schema.json   the JSON Schema
//   assets/styles/<stack>/…           the reference output for each stack (runtime/ excluded:
//                                     its source is assets/runtime/)
//   references/config.md              the structure + settings tables
//   scripts/lib/emit/runtime-assets.mjs  assets/runtime/* as strings, so the CLI
//                                     reads no skill files at run time (binary)
//
//   node scripts/dev/generate-fluid.mjs            write all of it
//   node scripts/dev/generate-fluid.mjs --check    write nothing; exit 1 if anything is stale, if a
//                                      fixture breaks an invariant, or if v1 parity fails
//
// The committed files are exactly this script's output. Never hand-edit them.

import { mkdirSync, writeFileSync, readFileSync, readdirSync, existsSync, rmSync } from 'node:fs'
import { dirname, join, resolve as resolvePath } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'
import { normaliseStructure, structureDefaults, jsonSchema, settingsSpec, STRUCTURE, STACKS, BAND_NAMES, bandBlurb, SKILL_VERSION, RESERVED_ROLE_NAMES } from '../../skills/fluid-design/scripts/lib/spec.mjs'
import { buildOutput } from '../../skills/fluid-design/scripts/lib/emit/project.mjs'
import { CORE, UI_FAMILY, EXTRA_FAMILIES } from '../../skills/fluid-design/scripts/lib/emit/tailwind.mjs'
import { num } from '../../skills/fluid-design/scripts/lib/emit/engine.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolvePath(__dirname, '../..')
const SKILL = join(ROOT, 'skills/fluid-design')
const FIXTURES = join(ROOT, 'tests/fixtures/configs')

// ── what the skill commits ──────────────────────────────────────────────

function exampleConfig() {
  const d = structureDefaults()
  return JSON.stringify({ $schema: './fluid.config.schema.json', ...d }, null, 2) + '\n'
}

function structureRows(node, path = '') {
  const rows = []
  for (const [k, child] of Object.entries(node.props)) {
    if (k === '$schema') continue
    const p = path ? `${path}.${k}` : k
    if (child.type === 'object') {
      rows.push([p + (child.toggle ? ' (or true/false)' : ''), '', child.doc ?? ''])
      rows.push(...structureRows(child, p))
    } else {
      const d = child.type === 'roles' ? JSON.stringify(child.default) : child.type === 'const' ? String(child.value) : JSON.stringify(child.default)
      const values = child.enum ? child.enum.map((e) => `\`${e}\``).join(' / ') : ''
      rows.push([p, d, `${child.doc ?? ''}${values ? ` (${values})` : ''}`])
    }
  }
  return rows
}

function configMd() {
  const s = normaliseStructure({})
  const specs = settingsSpec(s)
  const esc = (t) => t.replace(/\|/g, '\\|')
  const structureTable = structureRows(STRUCTURE)
    .map(([k, d, doc]) => `| \`${k}\` | ${d ? `\`${esc(d)}\`` : ''} | ${esc(doc)} |`)
    .join('\n')
  const bandTables = [...BAND_NAMES, null]
    .map((band) => {
      const rows = specs.filter((x) => x.band === band)
      if (!rows.length) return ''
      const title = band ? `### ${band}\n\n${bandBlurb(s, band)}.` : '### everywhere'
      return `${title}\n\n| Setting | Default | What it does |\n|---|---|---|\n${rows.map((r) => `| \`${r.name}\` | ${r.default === null ? 'unset' : `\`${num(r.default)}\``} | ${esc(r.doc)} |`).join('\n')}`
    })
    .filter(Boolean)
    .join('\n\n')
  return `<!-- GENERATED by scripts/dev/generate-fluid.mjs from scripts/lib/spec.mjs — do not edit. -->

# Configuration reference (fluid-design ${SKILL_VERSION})

Two kinds of configuration, split by one rule:

- **Structure** changes which CSS rules exist: which bands, their breakpoints,
  type roles, the prefix, output. It lives in \`fluid.config.json\` and needs
  \`fluid generate\`.
- **Settings** change a number inside those rules. They are CSS variables with
  registered defaults, set in your own \`:root\` (next to your tokens), live, no
  regenerate. The generated \`settings.reference.css\` lists them for a project.

## Structure: \`fluid.config.json\`

| Key | Default | What it does |
|---|---|---|
${structureTable}

## Settings: CSS variables

Every per-band setting is \`--fluid-<band>-<setting>\`. Numbers only, no units;
an invalid value falls back to the default. The role settings repeat for every
role in \`roles\` (a custom role starts with \`copy\`'s dampings). Tablet and
landscape have the same settings as phone. Shown here at the default structure.

${bandTables}

## Custom properties the engine owns

\`--fluid\`, \`--fluid-z\` (zoom on), \`--fluid-<role>\`, \`--fluid-ui\` (ui on),
\`--fluid-container-width\`, \`--fluid-container-padding\`, \`--fluid-header-h\`,
\`--fluid-safe-top\`, \`--fluid-safe-bottom\`, \`--fluid-browser-bar\`, \`--fluid-build\`. With
\`aliases\`: \`--fluid-chrome\`, \`--fluid-column\`, and the pre-namespace \`--header-h\`,
\`--safe-top\`, \`--safe-bottom\`, \`--browser-bar\`. Set by the runtime:
\`--fluid-zoom\`. Private: \`--_fluid-*\`. Never set any of these yourself; set
the settings they are built from.
`
}

function referenceOutputs() {
  const files = {}
  for (const stack of STACKS) {
    const s = normaliseStructure({ output: { stack } })
    const { files: out } = buildOutput(s)
    for (const [rel, content] of Object.entries(out)) {
      if (rel.startsWith('runtime/')) continue
      files[`assets/styles/${stack}/${rel}`] = content
    }
  }
  return files
}

const RUNTIME_SOURCES = ['fluid-units.js', 'fluid-units.d.ts', 'fluid-zoom.js', 'fluid-zoom.d.ts']

function runtimeAssets() {
  const entries = RUNTIME_SOURCES.map((f) => `  ${JSON.stringify(f)}: ${JSON.stringify(readFileSync(join(SKILL, 'assets/runtime', f), 'utf8'))}`)
  return `// GENERATED by scripts/dev/generate-fluid.mjs from assets/runtime/ — do not edit.\n// Edit the files in assets/runtime/, then run node scripts/dev/generate-fluid.mjs.\n\nexport const RUNTIME = {\n${entries.join(',\n')}\n}\n`
}

function allFiles() {
  return {
    'scripts/lib/emit/runtime-assets.mjs': runtimeAssets(),
    'assets/fluid.config.json': exampleConfig(),
    'assets/fluid.config.schema.json': JSON.stringify(jsonSchema(), null, 2) + '\n',
    'references/config.md': configMd(),
    ...referenceOutputs()
  }
}

// ── invariants every structure must keep ────────────────────────────────

function checkInvariants(label, structure, problems) {
  const { files } = buildOutput(structure)
  const css = files['fluid.css']
  const say = (m) => problems.push(`${label}: ${m}`)
  const code = css.replace(/\/\*[\s\S]*?\*\//g, '')
  if (/\bclamp\(/.test(code)) say('fluid.css uses clamp() (min()/max() only)')
  if (/\bround\(/.test(code)) say('fluid.css uses round()')
  const specs = settingsSpec(structure)
  const registered = (css.match(/^@property --fluid-/gm) || []).length
  if (registered !== specs.filter((x) => x.registered).length) say(`${registered} @property rules for ${specs.filter((x) => x.registered).length} registered settings`)
  const authoring = [css, files['_index.scss'] ?? '', files['fluid.stylex.ts'] ?? ''].join('\n')
  for (const x of specs) if (!authoring.includes(`var(${x.name},`)) say(`${x.name} is never read`)
  for (const r of structure.roles) if (!css.includes(`--fluid-${r}: calc(`)) say(`role ${r} has no unit`)
  if (structure.zoom !== css.includes('--fluid-z: calc(')) say(`--fluid-z ${structure.zoom ? 'missing' : 'emitted'} with zoom ${structure.zoom}`)
  if (structure.ui !== css.includes('--fluid-ui: calc(')) say(`--fluid-ui ${structure.ui ? 'missing' : 'emitted'} with ui ${structure.ui}`)
  if (structure.aliases && structure.ui && !css.includes('--fluid-chrome: var(--fluid-ui)')) say('aliases on but no --fluid-chrome')
  if (!structure.aliases && css.includes('--fluid-chrome')) say('aliases off but --fluid-chrome emitted')
  if (structure.output.base !== ('base.css' in files)) say('base.css presence does not follow output.base')
  if (structure.output.stack === 'tailwind-v4') {
    const u = structure.tailwind.utilities
    const fam = [['negative', /@utility -/], ['logical', /@utility [\w-]+-ps-\*/], ['basis', /@utility [\w-]+-basis-\*/], ['scroll', /@utility [\w-]+-scroll-mt-\*/], ['space', /@utility [\w-]+-space-x-\*/], ['rounded', /@utility [\w-]+-rounded-\*/]]
    for (const [k, re] of fam) if (u[k] !== re.test(css)) say(`utilities.${k} is ${u[k]} but the family is ${re.test(css) ? 'emitted' : 'missing'}`)
    for (const r of structure.roles) if (!css.includes(`@utility ${structure.prefix}-${r}-*`)) say(`no ${structure.prefix}-${r}-* utility`)
    if (structure.tailwind.variants !== css.includes('@custom-variant')) say('band variants do not follow tailwind.variants')
    if ((structure.tailwind.breakpoints === 'ladder') !== css.includes('--breakpoint-lg:')) say('breakpoint ladder does not follow tailwind.breakpoints')
  }
  if (structure.output.integration !== 'none' && !Object.keys(files).some((f) => f.startsWith('integrations/'))) say('integration requested but not emitted')
}

// ── main ────────────────────────────────────────────────────────────────

function main() {
  const check = process.argv.includes('--check')
  const files = allFiles()
  if (!check) {
    rmSync(join(SKILL, 'assets/styles'), { recursive: true, force: true })
    for (const [rel, content] of Object.entries(files)) {
      const abs = join(SKILL, rel)
      mkdirSync(dirname(abs), { recursive: true })
      writeFileSync(abs, content)
    }
    console.log(`[fluid-design] wrote ${Object.keys(files).length} files`)
    return
  }
  const problems = []
  for (const [rel, content] of Object.entries(files)) {
    const abs = join(SKILL, rel)
    if (!existsSync(abs)) problems.push(`missing: ${rel}`)
    else if (readFileSync(abs, 'utf8').replace(/\r\n/g, '\n') !== content) problems.push(`stale: ${rel}`)
  }
  // Every utility family's first word is a reserved role name, so a custom
  // role can never collide with one (fluid-<role>-* vs fluid-min-w-*).
  for (const [name] of [...CORE, ...UI_FAMILY, ...Object.values(EXTRA_FAMILIES).flat()]) {
    if (!RESERVED_ROLE_NAMES.has(name.split('-')[0])) problems.push(`utility family ${name}: "${name.split('-')[0]}" is not in RESERVED_ROLE_NAMES (spec.mjs)`)
  }
  const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))
  if (pkg.version !== SKILL_VERSION) problems.push(`package.json version ${pkg.version} is not SKILL_VERSION ${SKILL_VERSION} (spec.mjs): npm, the binaries and the lock stamp must agree`)
  checkInvariants('defaults', normaliseStructure({}), problems)
  const fixtures = readdirSync(FIXTURES).filter((f) => f.endsWith('.json')).sort()
  for (const f of fixtures) {
    const json = JSON.parse(readFileSync(join(FIXTURES, f), 'utf8'))
    delete json.$schema
    let s
    try {
      s = normaliseStructure(json)
    } catch (err) {
      problems.push(`fixture ${f}: ${err.message}`)
      continue
    }
    checkInvariants(`fixture ${f}`, s, problems)
  }
  const parity = spawnSync(process.execPath, [join(ROOT, 'tests/parity.mjs')], { encoding: 'utf8' })
  if (parity.status !== 0) problems.push(`v1 parity failed:\n${parity.stdout}${parity.stderr}`)
  if (problems.length) {
    console.error('[fluid-design] --check found problems:')
    for (const p of problems) console.error(`  ${p}`)
    console.error('Fix, then: node scripts/dev/generate-fluid.mjs')
    process.exit(1)
  }
  console.log(`[fluid-design] --check OK — ${Object.keys(files).length} generated files current, ${fixtures.length} fixture structures keep every invariant, v1 parity holds.`)
}

main()
