/**
 * GENERATED by fluid-design's generate-fluid.mjs — do not hand-edit.
 * Edit fluid.config.json and re-run:
 *   node scripts/generate-fluid.mjs --stack ts
 * 
 * Config:
 *   reference 1440x900, canvas 1680/80, engageAt 1024, heightAxis true
 *   fluid.floor 0.58
 *   display.damping 0.62 (floor auto -> 0.82)
 *   copy.damping 0.33 (floor auto -> 0.9)
 *   chrome.enabled true
 *   ceiling none
 *   prefix "fluid"
 */

/** Min-width (px) where the fluid scale turns on. Mirrors `engageAt` in
 * `fluid.config.json`. Every hand-typed `ENGAGE_QUERY`/`ENGAGE_BREAKPOINT_PX`
 * literal in this skill's motion ports (GSAP's `eases.ts`, React's
 * `lib/constants.ts`) should import THIS constant once your config's
 * `engageAt` stops matching the shipped default of 1024 — see each of
 * those files' own docblock for the literal this replaces. */
export const ENGAGE_PX = 1024

/** `matchMedia`-ready form of ENGAGE_PX. */
export const ENGAGE_QUERY = `(min-width: ${ENGAGE_PX}px)`

/** The viewport where every fluid unit equals exactly 1px — a content
 * budget, not the design canvas (references/fluid-scale.md §4). */
export const REFERENCE_WIDTH = 1440
export const REFERENCE_HEIGHT = 900

/** The drawn design-file frame: the `fluid-cap-*` grow-only ceiling
 * width, and its page gutter. */
export const CANVAS_WIDTH = 1680
export const CANVAS_GUTTER = 80
